### PR TITLE
Remove powerCost from triggered spells

### PR DESCRIPTION
**Pull request by killerwife**
@robinsch this should be more to your liking then.
@cala afaik we are missing it from all cores

Example: devastate triggers sunder armor for no cost. (possibly many more)

### CODE REVIEW

**Comment by robinsch** [comment]
No need to pass it as a parameter

**Comment by killerwife** [comment]
Its a static function

**Comment by cyberium** [comment]
Like @robinsch i think its better to remove that new argument.
CalculatePowerCost have then to be used only when we realy want to know that cost.
So everywere we can encounter triggered spell we have to add a check for it.

´´´cpp
uint32 powerCost = isTriggered ? 0 : CalculatePowerCost();
´´´
Or we can implement a more general method like GetPowerCost() and GetStaticPowerCost(...)?

**Comment by robinsch** [comment]
Remove the static and let it return 0 if spell is triggered

**Comment by killerwife** [comment]
@cyberium the function is used in 3 places, you require 100% exact code each time and we calculate it in AIs if the source needs to know if it has enough mana. I.e. you dont have spell*. Removing argument would mean the need for 2 equally same functions.

**Comment by cyberium** [comment]
@robinsch You probably think about something like this inside the method
```cpp
if (spell && spell->IsTriggered()
    return 0;
```
wich is smart too :)

@killerwife And? Just call it GetStaticPowerCost() within GetPowerCost() and handle the special case for instanciated Spell vs not instanciated only in second case. Because currently i dont see the point to send own spell pointer when calling CalculatePowerCost(...).

```cpp
m_powerCost = CalculatePowerCost(m_spellInfo, m_caster, this, m_CastItem); // << bad use of 'this' in this case because we are already in spell class.
```

**Comment by killerwife** [comment]
Then why dont we just send spellinfo in the first place?

**Comment by killerwife** [comment]
Nvm, scratch that, its because of applyspellmod, which is something i am working on reworking. Yuck.

**Pull request closed without merging**
