### PR TITLE
Event AI command.

### PR DESCRIPTION
**Pull request by Ulduar**
ACTION_T_SET_CONTROL_ATTACK -  control npc, allow run AttackStart function or not. Likely ReactPassive.
ACTION_T_SET_CURRENT_WAYPOINT - you can current waypoint for creature. Using creature_movement_template and creature_movement tables. You can link with db_script_on_creature_movement.

Example: Brutallus in Isle of Quel'Danas. Not in Sunwell. Cannot attack Madrigosa. Have events. Which can be performed using db_script_on_creature_movement.
Madrigosa in Sunwell Plateau not handled, but don't should attack start Brutallus after SpellHit Charge.
For Better Behaviour i can add DeleteThreatList, CombatStop and other needed for this case actions
Mu'ru summoned add (Void Sentinel and Void Spawn, Humanoids not have delay, you can attack start humanoids and get aggressive behaviour) have delay before attack. Control Attack can help this. Add on Spawn "Passive" reaction, after 3 second - remove and SetInCombatWithZone. 
For @xfurry 
Not ALL summoned npc have delay before attack. Bridge Event npc before Pathaleon in Mechanar not have delay, no need suggestion applied in core delay.
Kargath adds in Shattered Halls not have delay.
ACTION_T_SET_CURRENT_WAYPOINT can help.

Also Control Attack can used for invisible trigger, which should not be aggressive and have the AI.
Or any trigger without AI, but without aggressive behaviour. Broggok in Blood Furnace have invisible trigger for Poison spells. You can delete from SD2 and replace on EAI.

### CODE REVIEW

**Comment by killerwife** [comment]
I do not particularly like the waypoint thing. I have done something like that in SD2 and what it will do is have several instances of waypoint movement in stack, usually clearing top of the movement stack is sufficient, instead of forcing a waypoint point.

Feel free to disprove anything I just said.

**Comment by xfurry** [comment]
ACTION_T_SET_CURRENT_WAYPOINT -> No
ACTION_T_SET_CONTROL_ATTACK -> Maybe, but not in the current format. This is based on a patch that I wrote some time ago, in order to attempt to control eventAI scripted creatures to stop attacking on specific event (health percent as example). However, the current code is incomplete and doesn't work as per my expectations. So I think we need to rethink this concept.

**Comment by Ulduar** [comment]
Another response to expect and did not cost.

**Comment by cyberium** [comment]
Ok so it seem that this PR is not accepted as it is. Closing it.

**Comment by Ulduar** [comment]
In vain rejected by the way. I have two additional example.

**Comment by Phatcat** [comment]
@Ulduar You are always welcome to open up a new PR (you will probably have problems reopening this as you have deleted the repo) if you feel new stuff has surfaced which either backs up your changes (or proves a need for them) or you have refactored the work in such a way that it addresses the issues mentioned by killerwife and xfurry.

**Comment by Ulduar** [comment]
I will open him again and will close for various reasons.

**Comment by Phatcat** [comment]
Look, I cannot promise you that your code will be merged into master, but if it is needed to achieve a more blizzlike state, and you can prove it, and you are willing to incoorperate/address the feedback you get from others, then I frankly don't see why we'd close this.

I am sorry if you feel we were a bit too early on closing this before, I'll try to make sure that doesn't happen again if you do decide to re-open this issue, following what I said above, of course, because if you just PR the exact same changes as before, then it's probably going to get the exact same treatment I'm afraid.

**Comment by Phatcat** [comment]
Like for instance, take some screenshots or maybe record a video of how you imagined these would be used by the server; explain some reasons why you feel these commands should be available and what sort of functionality they give and how they improve on the current functionality towards a more blizzlike state or how it simplifies how we do eventAI currently. Anything, basically..

**Comment by Phatcat** [comment]
For instance, I think the SET_CURRENT_WAYPOINT is a good idea, as currently our escorts (and similar, like ZF stairs event) are having a hard time in that department, and what needs to happen is that the moment they enter combat, they should remember where they were standing, go fight, then run back to where they were standing (so we sort of need a current waypoint) and then continue the escort. Currently they either go back to their last known waypoint, or to the next, either of those are not blizzlike. also doing this allows us to set basically only 2 waypoints for scripted waypoints between straight lines. @cala you know I already mentioned something like this earlier.

Sure, Escorts may be SD2 and not EventAI, I don't know, but that changes nothing in my opinion, that only makes me think it should be added to both in either case.

**Comment by Ulduar** [comment]
1) I do not record video. Screenshot will give nothing
2) SET_CURRENT_WAYPOINT can be used not only Zul'Farak. Brutallus and Madrigosa in Quel'Danas side. Kil'jaeden outro event (Shattered Riftwalker npc) and so on. Examples of Cataclysm result will not - this is not an argument for developers.
3) For Kil'jaeden i have new idea. SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT.
Summon creature and Send AI Event for SET_CURRENT_WAYPOINT.
https://github.com/unified-db/Database/commit/0f04164420fcaab1f80c53a98c7ab99e9789b520
This is also can help complete this is script. With ACTION_T_ATTACK_START.


``` CPP
case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT_CUSTOM_EVENTAI_A:           
        {
            if (!pSource)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u found no worldobject as source, skipping.", m_table, m_script->id, m_script->command);
                break;
            }

            float x = m_script->x;
            float y = m_script->y;
            float z = m_script->z;
            float o = m_script->o;

            Creature* pCreature = pSource->SummonCreature(m_script->summonCreature.creatureEntry, x, y, z, o, m_script->summonCreature.despawnDelay ? TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN : TEMPSUMMON_DEAD_DESPAWN, m_script->summonCreature.despawnDelay, (m_script->data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL) ? true : false, m_script->textId[0] == 1);
((Creature*)pCreature)->AI()->SendAIEvent(AI_EVENT_CUSTOM_EVENTAI_A, nullptr, (Creature*)pCreature);
            if (!pCreature)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u failed for creature (entry: %u).", m_table, m_script->id, m_script->command, m_script->summonCreature.creatureEntry);
                break;
            }

            break;
        }
```

``` CPP
case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT_CUSTOM_EVENTAI_B:           
        {
            if (!pSource)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u found no worldobject as source, skipping.", m_table, m_script->id, m_script->command);
                break;
            }

            float x = m_script->x;
            float y = m_script->y;
            float z = m_script->z;
            float o = m_script->o;

            Creature* pCreature = pSource->SummonCreature(m_script->summonCreature.creatureEntry, x, y, z, o, m_script->summonCreature.despawnDelay ? TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN : TEMPSUMMON_DEAD_DESPAWN, m_script->summonCreature.despawnDelay, (m_script->data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL) ? true : false, m_script->textId[0] == 1);
((Creature*)pCreature)->AI()->SendAIEvent(AI_EVENT_CUSTOM_EVENTAI_B, nullptr, (Creature*)pCreature);
            if (!pCreature)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u failed for creature (entry: %u).", m_table, m_script->id, m_script->command, m_script->summonCreature.creatureEntry);
                break;
            }

            break;
        }
```

``` CPP
case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT_CUSTOM_EVENTAI_C:           
        {
            if (!pSource)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u found no worldobject as source, skipping.", m_table, m_script->id, m_script->command);
                break;
            }

            float x = m_script->x;
            float y = m_script->y;
            float z = m_script->z;
            float o = m_script->o;

            Creature* pCreature = pSource->SummonCreature(m_script->summonCreature.creatureEntry, x, y, z, o, m_script->summonCreature.despawnDelay ? TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN : TEMPSUMMON_DEAD_DESPAWN, m_script->summonCreature.despawnDelay, (m_script->data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL) ? true : false, m_script->textId[0] == 1);
((Creature*)pCreature)->AI()->SendAIEvent(AI_EVENT_CUSTOM_EVENTAI_C, nullptr, (Creature*)pCreature);
            if (!pCreature)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u failed for creature (entry: %u).", m_table, m_script->id, m_script->command, m_script->summonCreature.creatureEntry);
                break;
            }

            break;
        }
```

``` CPP
case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT_CUSTOM_EVENTAI_D:           
        {
            if (!pSource)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u found no worldobject as source, skipping.", m_table, m_script->id, m_script->command);
                break;
            }

            float x = m_script->x;
            float y = m_script->y;
            float z = m_script->z;
            float o = m_script->o;

            Creature* pCreature = pSource->SummonCreature(m_script->summonCreature.creatureEntry, x, y, z, o, m_script->summonCreature.despawnDelay ? TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN : TEMPSUMMON_DEAD_DESPAWN, m_script->summonCreature.despawnDelay, (m_script->data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL) ? true : false, m_script->textId[0] == 1);
((Creature*)pCreature)->AI()->SendAIEvent(AI_EVENT_CUSTOM_EVENTAI_D, nullptr, (Creature*)pCreature);
            if (!pCreature)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u failed for creature (entry: %u).", m_table, m_script->id, m_script->command, m_script->summonCreature.creatureEntry);
                break;
            }

            break;
        }
```

``` CPP
case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT_CUSTOM_EVENTAI_E:           
        {
            if (!pSource)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u found no worldobject as source, skipping.", m_table, m_script->id, m_script->command);
                break;
            }

            float x = m_script->x;
            float y = m_script->y;
            float z = m_script->z;
            float o = m_script->o;

            Creature* pCreature = pSource->SummonCreature(m_script->summonCreature.creatureEntry, x, y, z, o, m_script->summonCreature.despawnDelay ? TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN : TEMPSUMMON_DEAD_DESPAWN, m_script->summonCreature.despawnDelay, (m_script->data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL) ? true : false, m_script->textId[0] == 1);
((Creature*)pCreature)->AI()->SendAIEvent(AI_EVENT_CUSTOM_EVENTAI_E, nullptr, (Creature*)pCreature);
            if (!pCreature)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u failed for creature (entry: %u).", m_table, m_script->id, m_script->command, m_script->summonCreature.creatureEntry);
                break;
            }

            break;
        }
```

``` CPP
case SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT_CUSTOM_EVENTAI_F:           
        {
            if (!pSource)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u found no worldobject as source, skipping.", m_table, m_script->id, m_script->command);
                break;
            }

            float x = m_script->x;
            float y = m_script->y;
            float z = m_script->z;
            float o = m_script->o;

            Creature* pCreature = pSource->SummonCreature(m_script->summonCreature.creatureEntry, x, y, z, o, m_script->summonCreature.despawnDelay ? TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN : TEMPSUMMON_DEAD_DESPAWN, m_script->summonCreature.despawnDelay, (m_script->data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL) ? true : false, m_script->textId[0] == 1);
((Creature*)pCreature)->AI()->SendAIEvent(AI_EVENT_CUSTOM_EVENTAI_F, nullptr, (Creature*)pCreature);
            if (!pCreature)
            {
                sLog.outErrorDb(" DB-SCRIPTS: Process table `%s` id %u, command %u failed for creature (entry: %u).", m_table, m_script->id, m_script->command, m_script->summonCreature.creatureEntry);
                break;
            }

            break;
        }
```
Restrictions in the number of uint32 fields do not allow different.

**Comment by Phatcat** [comment]
> 3) For Kil'jaeden i have new idea. SCRIPT_COMMAND_TEMP_SUMMON_CREATURE_WITH_AI_EVENT.
Summon creature and Send AI Event for SET_CURRENT_WAYPOINT.
unified-db/Database@0f04164

this sounds a bit over the top, and I'm almost 100% certain that functionality could be achieved with a combination of temp summon and after it has recieved 'just summoned' call it could send an EventAI call to the temp summon, if that would even be needed, as I'm thinking it could be worked directly into the script/eventAI that that temp summon would use.

**Comment by Phatcat** [comment]
I just looked at the code example you provided.... I am not a fan of that execution... also I want to move away from manual summons as much as possible, whereever possible, this way of solving it helps nothing on summons cast natively. I don't think that is the route we want to go with this.

**Comment by Ulduar** [comment]
``` QUOTE
this sounds a bit over the top, and I'm almost 100% certain that functionality could be achieved with a combination of temp summon and after it has recieved 'just summoned' call it could send an EventAI call to the temp summon, if that would even be needed, as I'm thinking it could be worked directly into the script/eventAI that that temp summon would use.
```
No, we cannot Send Event for npc with the same entry, because the Event can go to the same NPC.
Example: Summon Riftwalker and set guid 200000 and 200001. Send Event. 200000 can be receive event twice in a row. No, not an option.
Between EventAI db_scripts and no of direct interaction.

``` CPP
I just looked at the code example you provided.... I am not a fan of that execution... also I want to move away from manual summons as much as possible, whereever possible, this way of solving it helps nothing on summons cast natively. I don't think that is the route we want to go with this.
```
As always, examples, and you throw overboard. As soon as this idea will give the developer - it will be immediately accepted. Examples train.

**Comment by Phatcat** [comment]
> Example: Summon Riftwalker and set guid 200000 and 200001. Send Event. 200000 can be receive event twice in a row. No, not an option.

then my argument goes back to this;

> I'm thinking it could be worked directly into the script/eventAI that that temp summon would use.

Just have the summoned mob behave how we tell it. If we can't do that because the same types of mobs have to behave differently during some event, then we script it, and we can handle each individual summon in SD2 I am almost sure of that.

**Comment by Ulduar** [comment]
``` QUOTE
we can handle each individual summon in SD2
```
Why don't allow db_scripts send ai event for temp summon creature.
And whta about https://github.com/unified-db/Database/commit/0f04164? Delete EAI and handle in SD2?

**Comment by Phatcat** [comment]
also we can't handle each individual summon in SD2 no, not the way I thought we could as least.

**Comment by Ulduar** [comment]
@Phatcat I prefer do without the SD2.

**Pull request closed without merging**
