### PR TITLE
Fix linker error

### PR DESCRIPTION
**Pull request by Lillecarl**
## 🍰 Pullrequest
Fixes linker error from https://github.com/cmangos/mangos-tbc/commit/a88c9d5fd3e1b99a77184e989497e90d03aec313

### Proof
image

### Issues
Fixes linker error from https://github.com/cmangos/mangos-tbc/commit/a88c9d5fd3e1b99a77184e989497e90d03aec313

### How2Test
Build core

### Todo / Checklist
- [X] None

### CODE REVIEW

**Comment by killerwife** [comment]
https://en.cppreference.com/w/cpp/string/basic_string/data This should not happen on a C++11 compliant compiler.

**Comment by killerwife** [comment]
Ahh, c++20. Omfg.

**Comment by Lillecarl** [comment]
clang
```
clang version 10.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/10.2.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
ld
`GNU ld (GNU Binutils) 2.35`
cmake
`cmake version 3.18.3`

**Comment by Lillecarl** [comment]
Thanks for the quick resolution!

**Pull request merged**
