### PR TITLE
[WorldState] Add CompleteWorldStateID to instance_dungeon_encounters for some cases that match default

### PR DESCRIPTION
**Pull request by AnonXS**
## 🍰 Pullrequest
```
10000	ZA - first 4 bosses dead - spawn Malacrass
71101	AQ40 - Battleguard Sartura - Alive
72801	SWP - Muru - Alive
```

### Proof
https://github.com/cmangos/issues/wiki/worldstate_name

### DB

https://github.com/cmangos/tbc-db/pull/1108

### CODE REVIEW

**Comment by Shauren** [comment]
In my opinion this should be changed to a set of conditions utilizing retail worldstate ids

| WorldStateId | Name |
|------|--------------|
| 3077 | Zul'Aman - Nalorakk - Encounter completed |
| 3122 | Zul'Aman - Akil'zon - Encounter completed |
| 3146 | Zul'Aman - Hex Lord Malacrass - Encounter completed |
| 3148 | Zul'Aman - Zul'jin - Encounter completed |
| 3152 | Zul'Aman - Halazzi - Encounter completed |
| 3153 | Zul'Aman - Jan'alai - Encounter completed |

**Comment by AnonXS** [comment]
They're changing these all the time so i think it's best if we stick with what we already have in DB.
"Encounter Table".

**Comment by Shauren** [comment]
Nah, those are unchanged for many years (ZA timed run worldstates are within the same range 3104 and 3106, check WorldStateUI.dbc - https://wow.tools/dbc/?dbc=worldstateui&build=2.4.3.8606#page=1&colFilter[1]=568) and are valid on retail even today

**Comment by AnonXS** [comment]
```ALTER TABLE instance_dungeon_encounters ADD COLUMN CompleteWorldStateID INT(11) NOT NULL DEFAULT '0' COMMENT 'Backported from later version';```

**Pull request closed without merging**
