### PR TITLE
Fix escort quests from gizelton caravan

### PR DESCRIPTION
**Pull request by miraco**
## 🍰 Pullrequest

This will fix both escort quests from gizeltone caravan.
Database changes from: https://github.com/cmangos/tbc-db/pull/1104 are needed
### Proof

- None

### Issues

- None

### How2Test

- None

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by miraco** [comment]
2 issues that happen with spawn-group/waypoint_path
1: When using waypoint_path (or maybe all movement tables atm) and having orientation set to 100 creatures should not change orientation <- thats not working. they always change facing
see https://youtu.be/b6kK0_oN8Nw?t=128

2 When they do the escort part and get attacked, the resetting looks rly strange and its possible that they dont line up again after.
see: https://youtu.be/b6kK0_oN8Nw?t=146

only video i currently have with retail behavior is this: https://youtu.be/qJFZROjBDek

**Comment by killerwife** [comment]
@AnonXS can u recheck this for me. If its k, then ill merge it.

**Comment by AnonXS** [comment]
grafik
grafik

wrong text / wrong location

**Comment by killerwife** [comment]
Closing this and will finish anons pr.

**Pull request closed without merging**
