### PR TITLE
Fix Health Funnel's spectacular "fake death" bug

### PR DESCRIPTION
**Pull request by Warlockbugs**
Interrupt channeled spells with periodic power cost if caster has insufficient power to keep channeling

### CODE REVIEW

**Comment by robinsch** [comment]
I would rather use some general check from CheckCast (CheckPower?), it should also return a error when there is not enough power (or health) to cast.

**Comment by cyberium** [comment]
This will not 'Fix' that issue it will just improve it. It will reduce drasticaly the frequence of that issue.
There is still the possibility to get 'GetPower()' exactly equal to 'manapersecond' resulting to set health to zero resulting of death animation folowed by resurecting due to health regen.
So is this spell is supposed to realy kill its caster? If yes we have to set death state too. If not we could use manapersecond + 1 to let at least 1 HP.

**Comment by killerwife** [comment]
Afaik stops at 1

**Comment by Warlockbugs** [comment]
It's supposed to stop when there is not enough health to transfer. Updated condition to cost+1.

**Comment by robinsch** [comment]
All of those things should be checked by CheckPower. You just need to call those checks or CheckCast at aura update. This should also fix other behaviours such as channeleing spells while out of range and so on.

**Comment by cyberium** [comment]
@robinsch CheckCast is not adapted for that, i mean too much uneeded check for this case. CheckPower well maybe but its a spell method and not static.
So proposed solution is acceptable. Maybe we'll have to add distence check later but even that iam not sure. I remeber such extra far cast from spell like arcane missiles
https://www.youtube.com/watch?v=iNYswLPteqo

**Comment by cyberium** [comment]
Well after more reviewing i conclude this is not the place to fix that issue,
Could you please test this patch -> https://github.com/cyberium/mangos-tbc/commit/8b7614a00d48f10e6d7a20564fb3598dffc9f632 and make your remark?

**Comment by Warlockbugs** [comment]
[8b7614a] (https://github.com/cyberium/mangos-tbc/commit/8b7614a00d48f10e6d7a20564fb3598dffc9f632) solves this (without the periodic cost mod though).

**Comment by cyberium** [comment]
ok remaining one thing, i encoutered cast of this spell that doing nothing due to pet have full life.
Is it supposed to be : 
- canceled
- do anyway the damage part
- let it cast and do nothing

**Comment by Warlockbugs** [comment]
I'd go with canceling. According to [WotLK era video] (https://www.youtube.com/watch?v=JYyHTlb2Lpw) they can't just keep it channeling more than 1 seconds (aka cancel before tick if the pet health is full).

**Comment by evil-at-wow** [comment]
I'd go with cancel as well. I can't say for sure what happened, but nowadays you can't even cast Health Funnel if your demon is full health (you get an error saying so). I don't remember what happened when your demon got back to full health because of the cast though, so I can't say for sure if it stopped channeling or just continued without much effect.

**Pull request closed without merging**
