### PR TITLE
backport c60c9d3 wotlk Allow spell effect 32 to trigger spells on unitTarget

### PR DESCRIPTION
**Pull request by hlarsen**

### CODE REVIEW

**Comment by killerwife** [comment]
I dont follow, why would u use unittarget when locks are done on GOs and GOs cant be untitarget.

**Comment by killerwife** [comment]
@hlarsen how does one reproduce the issue caused by this?

**Comment by Phatcat** [comment]
effect_32

**Comment by cyberium** [comment]
I dont see the point of this PR maybe more explanation will help?
How it should work, how it work, any reference to replicate it and any source?

**Comment by robinsch** [comment]
Point of this PR is to allow spells that have TARGET_FLAG_DEST_LOCATION to trigger spells.

**Comment by cyberium** [comment]
Nope, the effect 32 already trigger a spell.
The point for what i understaind is to add ability to cast that spell not on certain location but also on some UNIT if no TARGET_FLAG_DEST_LOCATION is provided.

So what i need is like i said a spell to reproduce this issue if it exist.

**Comment by robinsch** [comment]
Well as you said, any spell that has Effect 32 and TargetMask 0

**Comment by cyberium** [comment]
Seem this is not needed for tbc i cant find a fully implemented spell that can cause the issue.
As no one provide an exact issue i can close this.

**Pull request closed without merging**
