### PR TITLE
Can Not Interrupt Hurricane From Druid And NPC

### PR DESCRIPTION
**Pull request by Gelori**
Those two spells were totally missing InterruptFlags,
NPC could continue to cast even moving, added standard
15 flag
Issue:
	https://github.com/cmangos/issues/issues/1865

### CODE REVIEW

**Comment by killerwife** [comment]
I hate to be THAT guy, but (and especially since I am late to the party) but I bet one of these: ChannelIF 0x00007C0C is gonna have something to do with that.... Cos thats a whole load of flags right there.

**Comment by killerwife** [comment]
After further examination, tranquility has them. Will merge.

**Comment by BenDol** [comment]
out of curiosity, should an update file be produced for changes like this for `sql\updates\mangos\`?

**Comment by killerwife** [comment]
Nope, this is the correct workflow.

**Comment by BenDol** [comment]
so these changes need to be manually applied? I normally just run `InstallFullDB.sh` for all my mangosd changes :p

**Comment by killerwife** [comment]
No, they are automatically applied if you have CORE_DIR setup properly.

**Comment by BenDol** [comment]
Ah okay, nice thanks

**Pull request closed without merging**
