### PR TITLE
backport wotlk ce04030 move IsCastEndProcModifierAura to more fitting place

### PR DESCRIPTION
**Pull request by hlarsen**
this is actually an addition, it was not present in the mangos-tbc source.

### CODE REVIEW

**Comment by hlarsen** [comment]
looks like the last clang build wigged out on apt-get, should build ok, i just don't know how to kick off another build.

**Comment by killerwife** [comment]
@hlarsen squash the commits into two and explain to me what it should do

**Comment by cyberium** [comment]
well this is realy implemented in wotlk. But is this is realy needed for TBC and Classic?
@hlarsen do you understaind the exact purpose of this code? Can you explain it to us?

**Comment by hlarsen** [comment]
@cyberium sorry, missed the notifications before. this was listed on the [wiki](https://github.com/cmangos/issues/wiki/TBC-Backporting-TODO-WOTLK-Commits) as backport that needed to be done; i'm not aware of the need or issue it was supposed to fix.

**Comment by cyberium** [comment]
Ok all wiki backport and other not listed need testing unfortunatly, They are not just code that need to be applied :/

**Comment by robinsch** [comment]
Of course it's needed for TBC and Classic. Purpose of the code is that certain aura modifiers should be removed on cast finish rather then on cast start.

**Comment by cyberium** [comment]
same that for the other PR then i need a concrete exemple.

**Comment by robinsch** [comment]
SPELLMOD_RANGE
SPELLMOD_RADIUS
SPELLMOD_NOT_LOSE_CASTING_TIME
SPELLMOD_CASTING_TIME
SPELLMOD_COOLDOWN
SPELLMOD_COST
SPELLMOD_CASTING_TIME_OLD

**Comment by killerwife** [comment]
Problem with spellmods is that the whole system is horribly broken and doesnt work properly. I know about 11+ bugs in the current code, and its on my TODO list for some time. But yes, some modifiers are removed at the wrong time, I can second this.

**Comment by robinsch** [comment]
It's pretty okay - just has a few flaws that are fixed easily.

**Comment by killerwife** [comment]
Actually no, we even support spell_priority, which is crucial. Also we consume more than one of the same consumable spellmod, in addition we still consume shit on triggered spells, also we do not pass down spell mods from parent spell to triggered spells, and we can have disjoint counts of spellmods and spell aura charges in memory during spell execution.

**Comment by robinsch** [comment]
Well that's not even all, restoring spell mods and so on. But I mean it's like a 10 hour work thing. Not such a big deal imo

**Comment by killerwife** [comment]
Well, depends on the point of view I guess, it affects a ton of abilities ^^ Fixing it is not as hard as it is hard to know all the things you need to fix, before starting to fix it.

**Comment by cyberium** [comment]
@robinsch do you have that 6-10h to help cmangos community with your knowledge?

**Comment by robinsch** [comment]
Sadly no. Atleast not currently but I might port my work I did on the spellmod system when I find some time.

**Pull request closed without merging**
