### PR TITLE
Cyclonian quest DB to SD2

### PR DESCRIPTION
**Pull request by killerwife**
Author is @maximus

### CODE REVIEW

**Comment by Rushor** [comment]
the waypoints for him are already in db?

**Comment by killerwife** [comment]
@Rushor thx for that remark

INSERT INTO script_texts VALUES
('-1800003', 'Bath\'rah the Windwatcher begins a spell of summoning...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '2', '0', '0', ''),
('-1800002', 'Follow, $N. I will soon begin the summoning...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '0', '0', '0', '');

INSERT INTO script_waypoint VALUES
('6176', '0', '253.05', '-1459.09', '52.09', '2000', 'SAY_PROGRESS_1 and pause before running to summon location'),
('6176', '1', '256.87', '-1440.35', '50.09', '0', ''),
('6176', '2', '273.74', '-1433.18', '50.29', '0', ''),
('6176', '3', '297.77', '-1436.7', '46.96', '0', ''),
('6176', '4', '329.59', '-1442.08', '40.31', '0', ''),
('6176', '5', '332.73', '-1455.6', '42.24', '2000', 'pause before walking to summon location'),
('6176', '6', '323.83', '-1468.92', '42.24', '2000', 'pause before truning twards clyclonians spawn location'),
('6176', '7', '323.83', '-1468.92', '42.24', '12000', 'SAY_PROGRESS_2 and Summon Cyclonian, give 10 seconds for summon per spells cast time requirements and 2 seconds extra.'),
('6176', '8', '332.73', '-1455.6', '42.24', '0', 'runs back to spawn location'),
('6176', '9', '329.59', '-1442.08', '40.31', '0', ''),
('6176', '10', '297.77', '-1436.7', '46.96', '0', ''),
('6176', '11', '273.74', '-1433.18', '50.29', '0', ''),
('6176', '12', '256.87', '-1440.35', '50.09', '0', ''),
('6176', '13', '253.05', '-1459.09', '52.09', '0', ''),
('6176', '14', '250.84', '-1470.58', '55.4491', '0', '');

**Comment by cala** [comment]
Probably a stupid question from me, but I don't get what in this script is not doable by DBScripts.
I know the old script was pretty bad but it was remade by @Grz3s some times ago and IIRC it does the same thing that what I understand from that SD2 script.

**Comment by killerwife** [comment]
@cala Not really a stupid question. My understanding is that @devmaximus dislikes DBScripts :D

**Comment by killerwife** [comment]
@cala I asked @devmaximus about the script, and he gave me a simple answer: The timing of the dbscript is just simply not accurate enough for the script to be nice. Thats why he redid it in SD2.

**Comment by killerwife** [comment]
@cala can you just please look at how the script looks using this C++ and how it looks using dbscripts, compare, and lemme know what you think? Because there is quite a quality difference. I wanna process this PR one way or another.

**Comment by cala** [comment]
Alright, as requested I tested this PR against the DBScripts version and to be honest, I still don't understand why we need SD2 here. I'm sorry...

The timing and global looking is indeed better with the SD2 version because the NPC is set to run on various waypoints, but this can also be done with DBScripts. However, I noticed two issues with the SD2 script that are working well on the DBScript version:
- the quest is set as complete on event start (but item is not provided). This is wrong
- the required NPC is not summoned. It should be as it drops the item required for completion

My suggestion: this PR should be rejected and the DBScripts upgraded to add the run ON/OFF parts. Then, we should have the expected behaviour.
What do you think?

**Comment by killerwife** [comment]
If you are absolutely sure the difference can be added to the dbscript and the quality gain from SD2 will be negligible then yes, we should discard this SD2 and improve the dbscript.

**Comment by killerwife** [comment]
Added to DB and enhanced by @Saltgurka

**Pull request closed without merging**
