### PR TITLE
Rebase PR 320

### PR DESCRIPTION
**Pull request by Muehe**
## 🍰 Pullrequest

Just a rebase of #320 

### Issues
- None that I saw, would still appreciate a review

### How2Test
`./ExtractResources.sh a /path/to/client /path/to/output`

### TODO
- Port to classic/wotlk to replace:
    - cmangos/mangos-classic#399
    - cmangos/mangos-wotlk#279

### CODE REVIEW

**Comment by Muehe** [comment]
So, rebase² finished more or less.

One small problem remaining at the end of mmap extraction:

```
Building GameObject model Transportship.wmo.vmo
* Unable to open file
Building GameObject model Transport_Zeppelin.wmo.vmo
* Unable to open file
Building GameObject model Transportship_Ne.wmo.vmo
* Unable to open file
Building GameObject model Elevatorcar.m2.vmo
* Unable to open file
Building GameObject model Undeadelevator.m2.vmo
* Unable to open file
Building GameObject model Ironforgeelevator.m2.vmo
* Unable to open file
Building GameObject model Gnomeelevatorcar01.m2.vmo
* Unable to open file
Building GameObject model Gnomeelevatorcar02.m2.vmo
* Unable to open file
Building GameObject model Gnomeelevatorcar03.m2.vmo
* Unable to open file
Building GameObject model Gnomeelevatorcar03.m2.vmo
* Unable to open file
Building GameObject model Gnomehutelevator.m2.vmo
* Unable to open file
Building GameObject model Burningsteppselevator.m2.vmo
* Unable to open file
Building GameObject model Subwaycar.m2.vmo
* Unable to open file
Building GameObject model Ancdrae_Elevatorpiece.m2.vmo
* Unable to open file
Building GameObject model Mushroombase_Elevator.m2.vmo
* Unable to open file
Building GameObject model Cf_Elevatorplatform.m2.vmo
* Unable to open file
Building GameObject model Cf_Elevatorplatform_Small.m2.vmo
* Unable to open file
Building GameObject model Factoryelevator.m2.vmo
* Unable to open file
Building GameObject model Ancdrae_Elevatorpiece_Netherstorm.m2.vmo
* Unable to open file
```

Apart from that not much to say except that I basically skipped merging the things in the following screenshot orderly because it would have raised complexity a lot (with the conditions and whatnot) so now `OUTPUT_PATH`is basically a required parameter. No issue since `MoveMapGen.sh` is only called from `ExtractResources.sh` in two places, and both provide a path. Documentation that is probably already outdated anyway might have to be adjusted.

photo_2022-01-22_04-10-17

**Comment by berserkingyadis** [comment]
@killerwife 

This causes compilation errors on my windows machine.

New TerrainBuilder constructor doesnt fit the call in GeomData.cpp:149 anymore

image

call https://github.com/cmangos/mangos-tbc/blob/ce65ebca5c17cb0087ace7638907910b175a0955/contrib/recastdemomod/Source/GeomData.cpp#L149

callee https://github.com/cmangos/mangos-tbc/blob/ce65ebca5c17cb0087ace7638907910b175a0955/contrib/mmap/src/TerrainBuilder.h#L85

**Comment by berserkingyadis** [comment]
potential solution: adding explicit default parameter to constuctor in h file ?

```cpp
TerrainBuilder(bool skipLiquid, const char* workdir = nullptr)
```

**Comment by berserkingyadis** [comment]
added a PR. https://github.com/cmangos/mangos-tbc/pull/500

**Pull request closed without merging**
