### PR TITLE
Add cannot dodge while casting.

### PR DESCRIPTION
**Pull request by Yatzii93**
## 🍰 Pullrequest

Right now players can dodge attacks while casting. This is incorrect.
### Proof

- https://www.mmo-champion.com/threads/607978-dodge-while-ur-casting
- https://www.wowhead.com/forums&topic=86262

Struggling to find official proof but it seems common knowledge from people now and back in the day that this is the case. Similar to parry and blocking whilst casting.
### Issues

- Dodging attacks while casting.

### How2Test

- ".lookup spell dodge"
- Grab all the related dodge increase spells. Cast spells on an attacking mob.

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by killerwife** [comment]
@Warlockbugs

**Comment by killerwife** [comment]
I call bullshit :P But I've been known to be wrong.

**Comment by Yatzii93** [comment]
image

Ofcourse still not official. I've had atleast 3-4 people report it as a bug on my end, only now got around to looking into it.

Maybe someone can shed some official light on this.

**Comment by al3xc1985** [comment]
Dunno, but i remeber seeing movies with fire magea dodging while casting. Dunno for sure is very ling time since than

**Comment by Yatzii93** [comment]
Hmmm....honestly cannot find one reference online to someone saying it's possible aside from your comment xD

https://www.reddit.com/r/wow/comments/57vugc/can_someone_please_explain_how_blockdodgeparry/

**Comment by Warlockbugs** [comment]
It would fall in line with the rest (parry and block), but at the time i was writing this code, i couldn't find any more evidence. Your two links are probably only mentions i've seen so far. If someone can link a movie of a caster dodging an attack midcast, this would disprove it.

**Comment by Yatzii93** [comment]
I'm going to commit it to my core, the sweaty bois that play on my server are adament ^^. I'll revert if it's disproven.

**Comment by al3xc1985** [comment]
I will search the movie and prove it

**Comment by al3xc1985** [comment]
I come with update... I searched and could not find anything. all I found is that you can NOT dodge while casting

https://www.wowhead.com/forums&topic=86262
official info

so I believe the patch is viable

**Comment by Warlockbugs** [comment]
Confirmed through testing.

**Pull request merged**
