### PR TITLE
Fix Pyroclasm talent

### PR DESCRIPTION
**Pull request by Warlockbugs**
Adjust procFlags for all affected spells, include Soul Fire in core conditions.

### CODE REVIEW

**Comment by robinsch** [comment]
Just remove the else return line. All cases are should be covered by spell_proc_entry

**Comment by Warlockbugs** [comment]
Updated.

**Comment by cyberium** [comment]
is this needed for wotlk?

**Comment by Warlockbugs** [comment]
No, the talent was entirely changed in WotLK to provide bonus damage on crit.

**Comment by Phatcat** [comment]
> -                else
-                    return SPELL_AURA_PROC_FAILED;

Those 2 lines should stay in wrath then? (if they currently reside there at all) @robinsch ?

Also what is the issue with Pyroclasm currently?

**Comment by Warlockbugs** [comment]
If you read description of the talent in wrath, it has nothing to do with stuns anymore. It was revamped. If any stun related code exists in wrath branch, it should be removed.

**Comment by Phatcat** [comment]
Actually not looked into this in detail yet, just gathering as much information as I feel I maybe need before I do, so I won't have to sit around waiting for answers which I could have gotten beforehand had I just prepared myself a little. Sorry if some of my questions are very basic at times.

**Pull request closed without merging**
