### PR TITLE
Add a helper import script for the base database scripts

### PR DESCRIPTION
**Pull request by BenDol**
## 🍰 Pullrequest
Imports the base scripts automatically for you (with some basic configurations)

### How2Test
Run script.

### CODE REVIEW

**Comment by killerwife** [comment]
Suggestions:
Make it generate config on first use which you can fill up with your own data. Add the config to .gitignore. Same way as its done in all 3 DBs.

**Comment by berserkingyadis** [comment]
If this is used at db import/creation, could the creation script in sql/create be included in this script?

**Comment by BenDol** [comment]
@killerwife its just a once off import script when you need to reset your world data or w/e not sure we need to overdo it with configs personally. I use the prompts to stop the action when I use this script so I will likely leave it as is.

@berserkingyadis It could, I use it outside the creation of the actual create scripts. So prefer leaving it out or I could make it a configuration option.

**Comment by berserkingyadis** [comment]
I was thinking this could maybe be the core side equivalent of the InstallfullDB.sh

**Comment by cyberium** [comment]
@BenDol Please take in consideration @killerwife advise. The thing is separate data and script will permit to get script clean as we can add .config on gitignore list.
Also why not put that script directly in sql folder (not in base folder).

**Pull request closed without merging**
