### PR TITLE
Bunny20201210

### PR DESCRIPTION
**Pull request by cocely**
### Proof

- None

### Issues

- None

### How2Test

- None

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by cocely** [comment]
The push is wrong, please delete it

**Comment by ulfgebhardt** [comment]
Can we have the anticheat in the main repo pls?

**Comment by Muehe** [comment]
@cocely You mean the whole PR was a mistake? Best we can do is close it I think, but you should be able to do that yourself if that is what you want.

Deleting the commits from git is another problem altogether though, would probably require manual intervention and a force push.

**Comment by cocely** [comment]
@Muehe I mean is that I pushed the wrong branch myself, and I didn’t find out how to delete this commit,haha

**Pull request closed without merging**
