### PR TITLE
EAI: add ACTION_T_INFORM_PET

### PR DESCRIPTION
**Pull request by miraco**
## 🍰 Pullrequest

With this we have a better handling for Summoning NPCs that dont despawn when their owner dies.
https://github.com/cmangos/issues/issues/3755#issuecomment-2287088657

### Proof

- None

### Issues

- None

### How2Test

- None

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by killerwife** [comment]
Why not integrate it into send ai event to send to pet?

**Comment by miraco** [comment]
I tried adding TARGET_T_PET first so we can use it for more things
devenv_vgHNRmEbeb
but this never worked, target was always Target == nullptr

then i tried looking at boss scripts where this could get used and i found it working with this at mgt boss fight
devenv_JZJ3AvWkMw

and ACTION_T_THROW_AI_EVENT already has all 3 params in use so i thought its better using a new action for this

Imo the best way is so somehow add a new target like, TARGET_T_PET

**Comment by killerwife** [comment]
Problem is guardian != pet. Either way looking into it.

**Comment by killerwife** [comment]
Ok and why does ACTION_T_DESPAWN_GUARDIANS not help here? In the issue it was about despawning them on death right?

Not saying it fixes the whole situation.

**Comment by killerwife** [comment]
Okay, situation is as follows ->

ACTION_T_THROW_AI_EVENT from EAI - throws event around AI user and target is only used as action invoker, it doesnt really actually send the event to the guardian since you cant rly target one singular creature

SCRIPT_COMMAND_SEND_AI_EVENT - enables sending it to multiple targets but the system has no shorthand way of targeting guardians, the only way would be to assign these specific guardians a string id and target with those but then you could end up despawning spawns of a different master

Problem with targeting guardians is that its 1:N, and all of targeting in EAI is inherently 1:1 as it currently stands. I can add a SCRIPT_COMMAND_SEND_AI_EVENT equivalent to EAI, which will target a singular creature, however then we still have to solve the fact guardian targeting is 1:N. With the advent of string id, dbscripts have this issue inherently solved, since they can do 1:N.

So give me a rundown of what you want to do beyond despawn guardians, and I will model it upon that testcase. I get that you guys need a new possibility added here.

**Comment by miraco** [comment]
> Ok and why does ACTION_T_DESPAWN_GUARDIANS not help here? In the issue it was about despawning them on death right?
> 
> Not saying it fixes the whole situation.

No they shouldn’t instantly despawn  when their master dies.
They will only despawn on Reached Home (after Evade)

**Comment by killerwife** [comment]
Okay but thats default guardian behaviour. What spell are they summoned through?

**Comment by miraco** [comment]
> Okay but thats default guardian behaviour. What spell are they summoned through?

Yes it should be default guard behaviour, but this doesn’t seem to be working.

https://www.wowhead.com/classic/spell=12746/

**Comment by killerwife** [comment]
Now we are getting somewhere, will get back to you.

**Comment by miraco** [comment]
If you are you sure that this is default pet behaviour, we could prob just add a check here
https://github.com/cmangos/mangos-tbc/blob/27f97760bfa57d3774086b771593de08c46b2428/src/game/MotionGenerators/HomeMovementGenerator.cpp#L101

Something like 
if(!owner-IsAlive())
m_creature->despawn;

Or is there a flag that handle this?

**Comment by killerwife** [comment]
Check commits I made.

**Comment by miraco** [comment]
Works perfectly fine, ty

**Pull request closed without merging**
