### PR TITLE
Make Coilfang Frenzies not spawn in shallow water

### PR DESCRIPTION
**Pull request by insunaa**
## 🍰 Pullrequest

Stop Coilfang Frenzys spawning in the wrong places

### Proof

- None

### Issues

- Fixes https://github.com/cmangos/issues/issues/2425
### How2Test

- `.go cr morogrim`

### CODE REVIEW

**Comment by AnonXS** [comment]
i added comment ` // Exclude Water at Lady Vashj` so its visible why this "extra" is needed.

**Comment by killerwife** [comment]
1. This keyword is redundant. 2. Why the -20 check if I might ask? Isnt morogrim water puddle not swimmable?

**Comment by insunaa** [comment]
I like using the `this` keyword so that it's unambiguous to the reader what function is being called.
The -20 check is so that the frenzies don't spawn in the basin around Lady Vashj

**Comment by killerwife** [comment]
Lady vashj basin is confirmed to spawn fish, confirmed yday, and this keyword is not used per codestyle of cmangos. It is only to be used when context is unambiguous to the compiler.

**Comment by insunaa** [comment]
Alright, I'll remove the keyword and Z check

**Pull request closed without merging**
