### PR TITLE
Adjust threat generation for class abilities

### PR DESCRIPTION
**Pull request by Warlockbugs**
Nearly complete revamp for TBC. Values for abilities present in vanilla can be freely ported to classic as is, i think, because major re-balance happened only in WotLK.

### CODE REVIEW

**Comment by killerwife** [comment]
Pardon my jackass comment, but where the F do you have this data from ^^

**Comment by Warlockbugs** [comment]
@killerwife 
Lots of places, including, but not limited to: old EJ forums dumps, old official WoW-europe forums dumps, WoWWiki history, old threat meter addons sources.

**Comment by killerwife** [comment]
Fair enough, I am asking because this is one of those PRs where there is no way how to verify without doing the same work you did. We will see what the others have to say, because I myself am aware that TBC threat is crooked atm.

**Comment by robinsch** [comment]
I would say we need a proof for each specific change, there are also alot of coeff (other PR) that got changed in 2.3

**Comment by Warlockbugs** [comment]
@robinsch 
A proof in which form? Just a referring to the source and the date of the source?

**Comment by robinsch** [comment]
Yes.

**Comment by Warlockbugs** [comment]
Source legend (date & link):
EJ: [26 Jun 2008](https://web.archive.org/web/20081216020926/http://elitistjerks.com/f81/t18771-protection_guide/)
DTM: [04 Oct 2008](http://legacy.curseforge.com/media/files/201/513/DiamondThreatMeter_1.7.0_hybrid.zip)

9219b7d (Warrior) - EJ
b4964ac (Priest) - DTM
c2e53fb (Paladin) - DTM
281fcfe (Rogue) - DTM
d84e705 (Mage) - DTM
0a681fd (Shaman) - DTM
2735c00 (Warlock) - DTM
ed36af5 (Warrior) - DTM

**Comment by Warlockbugs** [comment]
Bump!
Just a note: Additional multirank redundancy cleanup (aka adding missing spells into spell_chain table to clean up "Rank 1", "Rank 2" spam in some cases) can be performed after both PRs (this one and [80](https://github.com/cmangos/mangos-tbc/pull/80)) are handled on top of them, because there are overlapping spells, which will result in conflict. Unless someone wants to resolve it by hand, of course, which i assume, not really. :simple_smile: The other option is to merge these 2 pull requests into one (add the other one on top of this one), but this can make reviewing them a bit less comfortable.

**Comment by Warlockbugs** [comment]
Rebased and updated with a fix for Mana Spring Totem fix.
Source: [Blue post] (https://web.archive.org/web/20160801184924/http://blue.mmo-champion.com/topic/18607-how-do-aggro-and-threat-work-in-wow/)
> Certain spells are exempt, for example mana from Blessing of Wisdom or a Mana Spring totem doesnt cause threat

**Comment by Phatcat** [comment]
But note that the blue post says

> for example mana from Blessing of Wisdom or a Mana Spring totem

-

> for example

What is special about Blessing of Wisdom and Mana Spring Totem?
The mana you get is provided by buffs, right? not by actively cast spells.

We sure this shouldn't be applied in a more generic way? Also sorry for my post-merge reply to a PR .. :/

**Comment by Warlockbugs** [comment]
Blessing of Wisdon and Mana Totem use different auras.
BoW uses SPELL_AURA_MOD_POWER_REGEN and in current codebase it doesn't cause threat as expected.
Totem uses SPELL_AURA_PERIODIC_ENERGIZE and this aura causes power gain threat. We can't simply adjust it for the aura itself, because abilities like Enrage, Bloodrage and Second Wind use it for generating rage (and threat too in that case). There are other uses for this aura, though: Drums of Regeneration, Feed Pet, Fel Mana Potion. We don't have data for threat generation for them, so i went with Blizzards's "exception" definition instead.

**Pull request closed without merging**
