### PR TITLE
Core/Player: Skip item SPELLTRIGGER_ON_USE at form change

### PR DESCRIPTION
**Pull request by robinsch**
This will fix auras casted from items with spell charges (e.g.: http://www.wowhead.com/spell=25211/heavy-golden-necklace-of-battle) disappearing on form change

### CODE REVIEW

**Comment by stfx** [comment]
Thanks. Since we are working on wotlk and backporting from there do you think you could make a PR against wotlk if this is needed there as well or is it only needed for TBC/Classic?

**Comment by robinsch** [comment]
The health pct thing is only for TBC and vanilla.

**Comment by stfx** [comment]
Alright, what about the SPELLTRIGGER_ON_USE?

**Comment by robinsch** [comment]
Can be used for all branches.

**Comment by evil-at-wow** [comment]
@stfx I can't reopen this PR - because the repository that submitted the PR has been deleted - but I'll have a good look at the TBC/Classic specific part now.

**Comment by stfx** [comment]
That part was regarding the health percent which is a separate PR: #32

**Comment by evil-at-wow** [comment]
@stfx I know, I just didn't notice it got its own PR.

**Pull request closed without merging**
