### PR TITLE
Implement Covert Ops script alpha/beta

### PR DESCRIPTION
**Pull request by Valkirie**
## 🍰 Pullrequest
Implement q.script 1079, 1080

### How it should work
1. Player to get close to either the Blue/Red Wagon and use its Explosives (item).
2. Explosives (item) will look for nearby banana (go, located under the map).
3. A TNT (go) has to be spawned on the wagon.
4. Players to standback and use its Detonator (item).
5. Detonator (item) will look for nearby TNT (go)
6. TNT (go) will be deleted, wagon (go) will be ignited (visual), banana (go) will be removed.
7. Nearby creatures will be called (running).
8. After xx seconds (900 in db), wagon should be returned to default state (visual), banana (go) respawned.

### Proof
https://www.youtube.com/watch?v=GSl1tx0s1Io

### Todo / Checklist
- [x] fix the hidden go despawn/respawn
- [x] fix the respawn timers
- [x] use gameobject table to handle dynamites spawn
- [ ] use creature guids instead of nearby creatures
- [ ] creatures to run to the explosion
- [ ] creatures to wander properly around the explosion and return to home

### sql request
```
-- Covert Ops - Alpha - Beta
UPDATE item_loot_template SET ChanceOrQuestChance = 100 WHERE entry = 5738;

REPLACE INTO scripted_event_id (id, ScriptName) VALUES ('691', 'event_covertops_detonate'); -- Remote Detonate (Red)
REPLACE INTO scripted_event_id (id, ScriptName) VALUES ('692', 'event_covertops_detonate'); -- Remote Detonate (Blue)
REPLACE INTO scripted_event_id (id, ScriptName) VALUES ('693', 'event_covertops_charge'); -- Set NG-5 Charge (Red)
REPLACE INTO scripted_event_id (id, ScriptName) VALUES ('694', 'event_covertops_charge'); -- Set NG-5 Charge (Blue)

UPDATE item_template SET ScriptName = "event_covertops_detonate" WHERE entry IN (5692, 5693);
UPDATE item_template SET ScriptName = "event_covertops_charge" WHERE entry IN (5694, 5695);

UPDATE gameobject_template SET ScriptName = 'go_covertops' WHERE entry IN (20899,19547);

-- GO_NG_5_EXPLOSIVES
DELETE FROM gameobject WHERE id IN (19592, 19601);
INSERT INTO gameobject (id, map, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecsmin, spawntimesecsmax)
VALUES (19592, 1, 1049.0312, -442.09897, 4.80105, 5.1487226, 0, 0, -0.53729916, 0.8433917, -1, -1),
(19601, 1, 1168.3534, 50.821724, 0.002397, 3.1590624, 0, 0, -0.99996185, 0.008734641, -1, -1);
```

### CODE REVIEW

**Comment by killerwife** [comment]
Finally got my hands on the sniff. These gos:
    GO_NG_5_EXPLOSIVES_RED = 19592,
    GO_NG_5_EXPLOSIVES_BLUE = 19601,
need to be moved to DB with negative spawntime.

This is their spawn data:
[0] Stationary Position: X: 1049.0312 Y: -442.09897 Z: 4.80105
[0] Stationary Orientation: 5.1487226
[0] GameObject Rotation: X: 0 Y: 0 Z: -0.53729916 W: 0.8433917
[0] OBJECT_FIELD_GUID: Full: 0x2C45AC002013220000000800000E307B GameObject/0 R4459/S8 Map: 1 Entry: 19592 Low: 929915
[0] OBJECT_FIELD_ENTRY: 19592
[0] OBJECT_DYNAMIC_FLAGS: 4294901760/NaN
[0] OBJECT_FIELD_SCALE_X: 1
[0] GAMEOBJECT_DISPLAYID: 191/2.68E-43
[0] GAMEOBJECT_PARENTROTATION + 3: 1065353216/1
[0] GAMEOBJECT_FACTION: 84
[0] GAMEOBJECT_BYTES_1: 1/8/0/255
[0] GAMEOBJECT_STATE_ANIM_ID: 208/2.91E-43

[0] Stationary Position: X: 1168.3534 Y: 50.821724 Z: 0.002397
[0] Stationary Orientation: 3.1590624
[0] GameObject Rotation: X: 0 Y: 0 Z: -0.99996185 W: 0.008734641
[0] OBJECT_FIELD_GUID: Full: 0x2C45AC002013244000000800000E2F62 GameObject/0 R4459/S8 Map: 1 Entry: 19601 Low: 929634
[0] OBJECT_FIELD_ENTRY: 19601
[0] OBJECT_DYNAMIC_FLAGS: 4294901760/NaN
[0] OBJECT_FIELD_SCALE_X: 1
[0] GAMEOBJECT_DISPLAYID: 191/2.68E-43
[0] GAMEOBJECT_PARENTROTATION + 3: 1065353216/1
[0] GAMEOBJECT_FACTION: 84
[0] GAMEOBJECT_BYTES_1: 1/8/0/255
[0] GAMEOBJECT_STATE_ANIM_ID: 208/2.91E-43

Also, there are specific guids which run, not all of them in the vicinity. Tons of mobs did not run to the explosives. Mostly mobs in the lumber mill (inside, not around, maybe a nice radius from center :P) and same with mine, from the mine entrance yes, not elsewhere around wagon. If you find time to work on it, great. If not, I will finish it when I have time.

**Comment by Valkirie** [comment]
`static const ExplosivesLocation aGameObjectExplosivesLocaitons[2] =
{
    {1049.00f, -442.11, 4.34f}, // guessed
    {1168.25f, 50.75f, 0.0f} // guessed
};`

I'm super proud of my guessed values. What do you technically mean by moving to db ?

**Comment by killerwife** [comment]
Insert into gameobject table with the given data. Spawntimesecsmin and max will be negative value (any really). In c++ you can then "respawn" the gameobject for X amount of time, instead of having to write all the code for spawning it.

**Comment by Valkirie** [comment]
Understood. Will do. Will also handle the targeted creatures through guids instead of radius around the wagon.

**Comment by Valkirie** [comment]
Sorry @killerwife, I'm super time constraint by COVID19 and struggle with the gameobject respawn once it has been despawned by the explosion. Plus I just can't get the creatures to run to the point then wander around it.

I'll let you handle this one and pay attention to the final code so I can learn from it.
> I updated the SQL request on top of the commit to reflect the gameobject INSERT query.

**Pull request closed without merging**
