### PR TITLE
Fix unstealthing on DoT damage

### PR DESCRIPTION
**Pull request by Warlockbugs**
Self-explanatory.

Fixes [#1008](https://github.com/cmangos/issues/issues/1008).

### CODE REVIEW

**Comment by killerwife** [comment]
Very, very, very baaaaaaaaad.

**Comment by Warlockbugs** [comment]
Perhaps, this is the step in right direction?

**Comment by killerwife** [comment]
https://github.com/killerwife/mangos-tbc/commit/d31322238e41b57ee0297f0b4df3239a3ae89878

this is what I was looking for

**Comment by Warlockbugs** [comment]
Too complicated for me. :( I'll just withdraw this pr.

**Pull request closed without merging**
