### PR TITLE
Spellscript component for beastmaster

### PR DESCRIPTION
**Pull request by insunaa**
## 🍰 Pullrequest

This PR adds the Spellscript component for the PTR Beastmaster NPC.

This is required to give the pets happiness and make them loyal + get training points after receiving them.

### How2Test

- Spawn Beastmaster (26307) and interact with him as a hunter

### CODE REVIEW

**Comment by killerwife** [comment]
We dont edit spelleffects anymore, separate it to a real spellscript.

**Comment by killerwife** [comment]
We dont edit spelleffects anymore, separate it to a real spellscript.

**Comment by insunaa** [comment]
> We dont edit spelleffects anymore, separate it to a real spellscript.

I was told by a prophet that you would say this, but I don't know where I should put it instead

**Comment by killerwife** [comment]
Same file as ur putting beastmaster npc

**Comment by insunaa** [comment]
> Same file as ur putting beastmaster npc

there is no beastmaster npc cpp

**Comment by insunaa** [comment]
updated this & db side PR. should now be mergeable.

**Comment by killerwife** [comment]
Closed in https://github.com/cmangos/mangos-tbc/commit/eb57bd3cf0d41ce0489d5df7c1a9df5aa9fbcf6a

**Pull request closed without merging**
