### PR TITLE
Experimental MinGW support

### PR DESCRIPTION
**Pull request by Warlockbugs**
This was something i was trying to get working for some time. :smile:

Summoning @cyberium @cala @xfurry 
## What is working at the moment:
- Building the realmd, mangosd and sd2 with MinGW toolchain.
- Building extractors with MinGW toolchain.
## What isn't working at the moment (known issues):
- WheatyExceptionReport due to lack of SEH handling (thanks to MSVC-only macros like __try()). [Do we actually need this?](http://www.programmingunlimited.net/siteexec/content.cgi?page=mingw-seh).
- Windows thread priority setting. native_handle_type is an int, not a windows handle here, any ideas?
- Cotire. Some Boost headers make MinGW very sad with resulting circular winsock includes.
- CMake for some reason wants to install the mangosd library file (.a) along the executable into "bin". 
- More stuff? I didn't get to do an exhaustive test of all build configurations.
## Improvement prospects:
- Try to move out preprocessor definitions from dependencies' code into cmakelists where (and if) possible? That probably may try to take away some burden if someone decides to update some of the dependencies, but at cost of preprocessor branching transparency.
## Test platform:
- Windows 10 x64
- CMake 3.6.1
- MinGW-w64 (x86 mode) 5.3.0 (exceptions: dwarf, threads: posix)
- Boost 1.61.0 (built as static release with MinGW)
## Demo binaries:

Release 76d0dc5 with this patch applied on top of it, built in configuration mentioned earlier.
[Download link](https://www.dropbox.com/s/np2i73paqkksz07/cmangos-tbc-76d0dc5-mingw-530-x86.7z?dl=1)

### CODE REVIEW

**Comment by Warlockbugs** [comment]
Added support for ad and MoveMapGen. Building vmap extractor depends on having bzip library, which we don't include within the project files. Should we?

**Comment by Warlockbugs** [comment]
Added support for building VMap extractors.

**Comment by Warlockbugs** [comment]
I am virtually done with this PR, unless someone knows how to resolve issues mentioned in the post. Any feedback on the subject?

**Comment by killerwife** [comment]
People who usually like things like these are not very active, I suggest you let it sit here for a while. Maybe @Fabi will know someone who is interested.

**Comment by Lillecarl** [comment]
If it doesn't break anything else, I don't see why waiting is important.

**Comment by Warlockbugs** [comment]
In addition to known issues in the header, there are linking issues, which occur only in debug mode, i.e. its currently not possible to use MinGW toolchain for development. That's what personally holds me off.

If its somehow specific to my own test configuration (Boost being static and all) and all build modes work for your MinGW distribution, then i can cross it out.

**Comment by Lillecarl** [comment]
I'm setting a reminder to test this weekend!

**Comment by Warlockbugs** [comment]
This PR is now outdated and was reimplemented with new project structure.
Related commits:
https://github.com/cmangos/mangos-classic/commit/7178ec19614bd79b9ce9f6e3e4afd2a3eded5172
https://github.com/cmangos/mangos-classic/commit/d70acf3d6de524dd53237cb054ea7eb222005ca0
https://github.com/cmangos/mangos-classic/commit/c73a876293e720a1fab2e93da76c7d9941a3e6ac
https://github.com/cmangos/mangos-classic/commit/6664c4f0bcdb96315c458d01e5861947abb5824d
https://github.com/cmangos/mangos-classic/commit/b3788b59e80db819b783257e8315c90b1ec33291
https://github.com/cmangos/mangos-classic/commit/c8074475200a5063c64b2dcfe0039ac4d409a913
https://github.com/cmangos/mangos-classic/commit/0f9c806cdb522dc500775981a718ffaf07067f65
https://github.com/cmangos/mangos-classic/commit/6a96d69e839fba35d984835b43af7ca37f4b2688

**Pull request closed without merging**
