### PR TITLE
WIP: Warden Anticheat Implementation

### PR DESCRIPTION
**Pull request by BenDol**
## 🍰 Pullrequest
Warden Anticheat for TBC (classic version was incomplete). There are actually no memory addresses for TBC client yet I don't think? Not really sure. But anyway will leave this open for anyone.

Has a BUILD_ANTICHEAT definition/module.

### Issues
Less cheats is good 👍 

### How2Test
Enable the profile and compile, then get the memory addresses for TBC client cheats?

### Todo / Checklist

- [x] CMake profile/definition BUILD_ANTICHEAT
- [ ] Socket architecture to decouple Warden
- [ ] Finalize the SQL imports

### CODE REVIEW

**Comment by keyshuwen** [comment]
emmm... ...

Maybe that's what you want.   :)  

@BenDol   

--
-- Dumping data for table `warden`
--

 LOCK TABLES `warden` WRITE;
/*!40000 ALTER TABLE `warden` DISABLE KEYS */;
INSERT INTO `warden` VALUES (1, 1, 8606, 243, '', '', 4840352, 2, '558B', 'LUA Protection');
INSERT INTO `warden` VALUES (2, 2, 8606, 243, '', '', 8979979, 5, 'E04D62503F', 'Hyper Speed');
INSERT INTO `warden` VALUES (3, 3, 8606, 243, '', '', 9208923, 5, 'C0854A3340', 'Gravity');
INSERT INTO `warden` VALUES (4, 4, 8606, 243, '', '', 8100062, 2, '7541', 'Air Jump');
INSERT INTO `warden` VALUES (5, 5, 8606, 243, '', '', 4912599, 2, '7509', 'Anti AFK');
INSERT INTO `warden` VALUES (6, 6, 8606, 243, '', '', 6638471, 2, '741E', 'Model Hack');
INSERT INTO `warden` VALUES (7, 7, 8606, 243, '', '', 5524941, 2, '7F17 ', 'Show Levels');
INSERT INTO `warden` VALUES (8, 8, 8606, 243, '', '', 6160566, 6, '8B80E0100000', 'Tracking');
INSERT INTO `warden` VALUES (9, 9, 8606, 243, '', '', 6181252, 6, '8BB1E4100000', 'World Tracking');
INSERT INTO `warden` VALUES (10, 10, 8606, 217, '', 'WPESPY.DLL', 0, 0, '', 'WPE PRO - Injected DLL');
INSERT INTO `warden` VALUES (11, 11, 8606, 217, '', 'RPE.DLL', 0, 0, '', 'rEdoX Packet Editor - Injected DLL');
INSERT INTO `warden` VALUES (12, 12, 8606, 217, '', 'ICANHAZSPEED.DLL', 0, 0, '', 'ICanHazSpeed - Injected DLL');
INSERT INTO `warden` VALUES (13, 13, 8606, 217, '', 'MAELSTROM_KEYS_HOOK.DLL', 0, 0, '', 'Maelstrom - Injected DLL');
INSERT INTO `warden` VALUES (14, 14, 8606, 217, '', 'MAELSTROM_MESS_HOOK.DLL', 0, 0, '', 'Maelstrom - Injected DLL');
INSERT INTO `warden` VALUES (15, 15, 8606, 217, '', 'SETPRIV.DLL', 0, 0, '', 'HideToolz - Injected DLL');
INSERT INTO `warden` VALUES (16, 16, 8606, 217, '', 'SPEEDHACK.DLL', 0, 0, '', 'Cheat Engine - Injected DLL');
INSERT INTO `warden` VALUES (17, 17, 8606, 243, '', '', 8095301, 2, '7513', 'Air Jump 2');
INSERT INTO `warden` VALUES (18, 18, 8606, 243, '', '', 9208728, 4, 'BB8D243F', 'Wallclimb');
INSERT INTO `warden` VALUES (19, 19, 8606, 243, '', '', 6518444, 2, 'DECA', 'Wallclimb 1');
INSERT INTO `warden` VALUES (20, 20, 8606, 243, '', '', 8095954, 3, '8B4908', 'Teleport To Plane 2');
INSERT INTO `warden` VALUES (21, 21, 8606, 243, '', '', 8095957, 3, '894808', 'Teleport To Plane');
INSERT INTO `warden` VALUES (22, 22, 8606, 243, '', '', 8103107, 3, '894E3C', 'No Fall DMG');
/*!40000 ALTER TABLE `warden` ENABLE KEYS */;
UNLOCK TABLES;

**Comment by BenDol** [comment]
@keyshuwen thank you for the contribution! :)

**Comment by cyberium** [comment]
Good part of the work is already done. Thats nice to see.
Warden should be fully optional. Sql part can part of the base. The service should be independant of the server and if possible can be stopped relaunched without problems.
Once the code will be enough mature i doubt the code base will have to change often over time.
Idea is to make it educative for those who want to learn how it work.
I hope you'll get some time to work on it. Iam not so interested on that but iam ok to include it if its interesting code that may benefit to others.

**Comment by BenDol** [comment]
I will foot this task when I have time, probably a little lower on my priority list right now though.

**Comment by Yatzii93** [comment]
Im sure u already know but I'll post it just incase: 
Currently it's getting stuck at Handle data.
```
2019-06-08 05:26:52 Server side warden for client 8 (build 8606) initializing...
2019-06-08 05:26:52 C->S Key: 4FE6E6191FF872AEEDE2A87A2932FB18
2019-06-08 05:26:52 S->C Key: 27147E9CDC2DFD850042E286F43A6896
2019-06-08 05:26:52   Seed: 4D808D2C77D905C41A6380EC08586AFE
2019-06-08 05:26:52 Loading Module...
2019-06-08 05:26:52 Module Key: AE25BC51063B77BD363C3EFE0FC173F9
2019-06-08 05:26:52 Module ID: 79C0768D657977D697E10BAD956CCED1
2019-06-08 05:26:52 Request module
2019-06-08 05:26:52 Got packet, opcode 01, size 1
2019-06-08 05:26:52 Handle data
2019-06-08 05:32:07 Server side warden for client 6 (build 8606) initializing...
2019-06-08 05:32:07 C->S Key: 85C9AD01B7568238CE999D665C475C19
2019-06-08 05:32:07 S->C Key: 9C199D98444E994CF12DB759D5319804
2019-06-08 05:32:07   Seed: 4D808D2C77D905C41A6380EC08586AFE
2019-06-08 05:32:07 Loading Module...
2019-06-08 05:32:07 Module Key: AE25BC51063B77BD363C3EFE0FC173F9
2019-06-08 05:32:07 Module ID: 79C0768D657977D697E10BAD956CCED1
2019-06-08 05:32:07 Request module
2019-06-08 05:32:07 Got packet, opcode 00, size 1
2019-06-08 05:32:07 Send module to client
2019-06-08 05:32:07 Got packet, opcode 01, size 1
2019-06-08 05:32:07 Handle data
```

**Comment by BenDol** [comment]
I think it might be the latest commit I was experimenting with, I will look into Warden some more later. Thanks for the update!

**Comment by al3xc1985** [comment]
Any news with this @BenDol ?

**Comment by Lymphome** [comment]
Successfull build on last core revision (s2414).

I found some more checks and add them to keyshuwem list :

INSERT INTO `warden` VALUES 
  (1,1,8606,217,'','WPESPY.DLL',0,0,'','WPE PRO - Injected DLL'),
  (2,2,8606,217,'','RPE.DLL',0,0,'','rEdoX Packet Editor - Injected DLL'),
  (3,3,8606,217,'','ICANHAZSPEED.DLL',0,0,'','ICanHazSpeed - Injected DLL'),
  (4,4,8606,217,'','MAELSTROM_KEYS_HOOK.',0,0,'','Maelstrom - Injected DLL'),
  (5,5,8606,217,'','MAELSTROM_MESS_HOOK.',0,0,'','Maelstrom - Injected DLL'),
  (6,6,8606,217,'','SETPRIV.DLL',0,0,'','HideToolz - Injected DLL'),
  (7,7,8606,217,'','SPEEDHACK.DLL',0,0,'','Cheat Engine - Injected DLL'),
  (8,8,8606,217,'','SPEEDHACK-X86_64.DLL',0,0,'','SPEED HACK - Injected DLL'),
  (9,9,8606,217,'','IHOOK.DLL',0,0,'','ASM - Injected DLL'),
  (10,10,8606,217,'','WHITEMAGIC.DLL',0,0,'','Application Inject Library - Injected DLL'),
  (11,11,8606,217,'','GREYMAGIC.DLL',0,0,'','Automation Botting Library - Injected DLL'),
  (12,12,8606,217,'','BLACKMAGIC.DLL',0,0,'','Memory Inject Library - Injected DLL'),
  (13,13,8606,217,'','SZATYOR.DLL',0,0,'','Packet Sniffer - Injected DLL'),
  (1001,1001,8606,243,'','',4840352,2,'558B','LUA Protection'),
  (1002,1002,8606,243,'','',8979979,5,'E04D62503F','Hyper Speed'),
  (1003,1003,8606,243,'','',9208923,5,'C0854A3340','Gravity'),
  (1004,1004,8606,243,'','',8100062,2,'7541','Air Jump'),
  (1005,1005,8606,243,'','',4912599,2,'7509','Anti AFK'),
  (1006,1006,8606,243,'','',6638471,2,'741E','Model Hack'),
  (1007,1007,8606,243,'','',5524941,2,'7F17 ','Show Levels'),
  (1008,1008,8606,243,'','',6160566,6,'8B80E0100000','Tracking'),
  (1009,1009,8606,243,'','',6181252,6,'8BB1E4100000','World Tracking'),
  (1010,1010,8606,243,'','',8095301,2,'7513','Air Jump 2'),
  (1011,1011,8606,243,'','',9208728,4,'BB8D243F','Wallclimb'),
  (1012,1012,8606,243,'','',6518444,2,'DECA','Wallclimb 1'),
  (1013,1013,8606,243,'','',8095954,3,'8B4908','Teleport To Plane 2'),
  (1014,1014,8606,243,'','',8095957,3,'894808','Teleport To Plane'),
  (1015,1015,8606,243,'','',8103107,3,'894E3C','No Fall Time'),
  (1016,1016,8606,243,'','',4896176,5,'A1CCECC600','GetCamera'),
  (1017,1017,8606,243,'','',6321600,6,'8B81D40E0000','GetModel'),
  (1018,1018,8606,243,'','',7641168,6,'8B0D14F8E100','OsGetAsyncTimeMs'),
  (1019,1019,8606,243,'','',7146485,2,'FFD2','Warden Related'),
  (1020,1020,8606,243,'','',6583320,2,'7413','ModelHack 2'),
  (1021,1021,8606,243,'','',6377767,3,'0F8560','NameplatePatch'),
  (1022,1022,8606,243,'','',6563465,2,'F3A5','TimeSetPatch'),
  (1023,1023,8606,243,'','',6559495,2,'8931','TimeSetPatch2'),
  (1024,1024,8606,243,'','',4653019,3,'83F803','GlueXML_SignaturePatch'),
  (1025,1025,8606,243,'','',5433092,2,'743C','GlueXML_RenamePatch'),
  (1026,1026,8606,243,'','',4774481,3,'0F8465','TranslatePatch'),
  (1027,1027,8606,243,'','',4840370,2,'7465','Lua_Patch'),
  (1028,1028,8606,243,'','',9208732,4,'3630613F','MountainClimbPatch'),
  (1029,1029,8606,243,'','',4785563,2,'7520','LanguageRestriction'),
  (1030,1030,8606,243,'','',4912512,2,'7460','AFK Jump'),
  (1031,1031,8606,243,'','',8103104,3,'8B4F7C','NoFallDamage');

ID starting at 1 : DLL
ID starting at 1000 : memory checks

No deep tests made : 
* no kick with wowme
* no kick because using wine (good for me :))

A list for wotlk can be seen here :
http://www.ac-web.org/forums/showthread.php?227605-Warden-Checks-WoTLK
(take care of "false positive" noticed at the end of the thread, don't kick/ban wine users ! :) )

**Comment by Kalorte** [comment]
Hey, any news about this ? :)

**Comment by yuanf225** [comment]
Hey, any news about this ? :)

**Comment by cyberium** [comment]
Sorry we dont support warden that way.

Separate and standalone project is preferable.

**Comment by al3xc1985** [comment]
@BenDol hey don't u have time to update to the right standard asked by cyberium? it would e really nice to have it implemented the right way

**Pull request closed without merging**
