### PR TITLE
Adjust bonus power coefficients for class abilities and spells

### PR DESCRIPTION
**Pull request by Warlockbugs**
More realistic TBC coefficients for casters, fix for obvious mistakes (such as Rain of Fire), fix for hidden bug (Ignite talent should not receive bonus spell power) and cleanup (Living Bomb is WotLK spell).

### CODE REVIEW

**Comment by killerwife** [comment]
Just a quick note. Run server and see if you made any errors. Afaik those dataz are req only to be added for rank 1.

**Comment by robinsch** [comment]
Where do you get them from?

**Comment by Warlockbugs** [comment]
@killerwife 
I added only first Rank for spells mentioned in spell_chain. Hidden triggered proc effects require manual handling.

@robinsch
Sources are scattered.
A huge chunk came from [WoWWiki archive](http://wowwiki.wikia.com/wiki/Spell_power_coefficient?oldid=1549180), but i had to look up old versions of theorycrafting addons (such as DrDamage) and even spreadsheets for some of them.

**Comment by Warlockbugs** [comment]
More item entries and Hunter corrections. Squashed and rebased to ease reviewing.

**Comment by Warlockbugs** [comment]
That's it for now, i've stopped updating this PR to let others review.

@robinsch 
As you requested in another PR, sources for this PR.

Source Legend:
WW: [27 Jul 2008](http://wowwiki.wikia.com/wiki/Spell_power_coefficient?oldid=1549180)
DrD: [28 Sep 2008](http://www.wowace.com/media/files/126/551/DrDamage-r81778.1.zip)
HDC: [31 Jul 2008](http://dungeonkeepers.ucoz.com/_fr/2/Hunter_DPS_Calc.xls) 
LO: [11 May 2006](https://web.archive.org/web/20160722143219/http://leftoversraiding.org/index.php/topic/1895/1/arcane-damage-and-you-(or-um-spelldamage-you're-kidding-right).html) (Should still be correct for TBC, SP got revamped in WotLK) 

Druid:
Everything - WW

Hunter:
Arcane Shot - LO (arcane damage), DrD
Scatter Shot - DrD
Silencing Shot - DrD
Steady Shot - DrD, HDC
Serpent Sting - LO (nature damage), DrD, HDC
Volley - LO (arcane damage)

Mage:
Arcane Missiles - DrD
Fire Ward - DrD
Frost Ward - DrD
Ignite - Bug fix (this is a talent proc, should receive no scaling)
Everything else - WW

Paladin:
Blessing of Sanctuary - Bug fix (no scaling)
Judgement of Blood Proc - Bug fix (no scaling)
Seal of Blood Proc - Bug fix (no scaling)
Everything else - WW

Priest:
Everything - WW

Rogue Poisons:
Everything - Bug fix (no scaling, RIP spellpower rogue bugspec)

Shaman:
Chain Lightning - DrD
Everything else - WW

Warlock:
Everything - WW

Items:
Arcane Infused Gem - LO
Everything else - Bug fix (items that shouldn't scale, but are frequently abused)

**Comment by Warlockbugs** [comment]
I've noticed Ferocious Bite damage was off, so i've correct this one too before this PR is reviewed. Ferocious Bite coefficient is corrected and moved into database.

**Comment by robinsch** [comment]
Ferocious Bite should also scale with combopoints (3% of AP per CP)

**Comment by killerwife** [comment]
Yes but that can hardly be done in DB

**Comment by robinsch** [comment]
This was not related to this PR rather then to his comment of the damage being off (and still being off).

**Comment by killerwife** [comment]
I know, Im sure that he will look into it now that uve alerted him :)

**Comment by Warlockbugs** [comment]
Reverted DB change, applied CP scaling instead according to [archived article](https://web.archive.org/web/20081220000111/http://druid.wikispaces.com/Druid_Game_Mechanics#toc21).

**Pull request closed without merging**
