### PR TITLE
Implement new command to make easier to debug single object.

### PR DESCRIPTION
**Pull request by cyberium**
## 🍰 Pullrequest
Console log might be a nightmare to read when debuging specific creature. You have to do with all loaded creature that move, melee, cast...

With this patch you are now able to select one or more object to make everything quiet but the chossen unit.

You can also filter all object type so event related to let say players will only be logged.

As some instruction are added for log and there are many call to log i also added a compilation directive so we can disable all log at once by undefining NDEBUG.
That way Release will not be impacted and can even be a little bit faster than before.

Commands added

> server log guidfilter #guid
> server log typefilter #player, creature, item, gob...
> logtarget (add selected unit to the log list)

These commands should be used with filter commands
> server log filter #filtername off

So filter filename is disabled and you are able to see log.
filtername can be "all" so in one command you can enable/disable all filters.

I think this can help alot db dev and even core dev for debugging.

### Issues
- too logs in debug mode in the console

### How2Test

You have to use ```server log filter off``` command in the console.
If you want to use following command in the game chat you have to do
```sql
UPDATE `command` SET `security`='3' WHERE `name` LIKE "server log%";
```

- Merge this code
- .server log filter all off
- .go c hogger
- select hogger as a target
- .logtarget

### CODE REVIEW

**Comment by berserkingyadis** [comment]
`.server log filter all off` has to be written in server console, unless you change its security level.

After disabling all filters and focussing the logtarget on hogger, I got his log output (Attempting to cast some spells, movement..) and when I attacked him some of the combat. 

```
CreatureEventAI: Event type 4 (script 47802) triggered for Creature (Entry: 478 Guid: 99744) (invoked by Player Faerlina (Guid: 19))
Command: damage 1 [Player: Faerlina (Account: 5) X: -9971.908203 Y: 623.641296 Z: 38.702328 Map: 0 Selected: Creature (Entry: 478 Guid: 99744)]
WORLD: Sent SMSG_AI_REACTION, type 2.
WORLD: Sent SMSG_ATTACKSTART
Creature (Entry: 478 Guid: 99744) chase to Player Faerlina (Guid: 19)
++ PathFinder::PathInfo for 99744

++ PathFinder::calculate() for 99744

++ BuildPolyPath :: (!startPolyFound && !endPolyFound)

++ PathFinder::BuildPointPath path type 1 size 3 poly-size 2

RollMeleeOutcomeAgainst: New attack die: [MISS:1520, DODGE:1476, PARRY:0, BLOCK:0, GLANCE:0, CRIT:0, CRUSH:0]
RollMeleeOutcomeAgainst: Rolled 4114, result: HIT
WORLD: Sending SMSG_ATTACKERSTATEUPDATE
DealDamageStart
deal dmg:12 to health:2804
DealDamageAlive
DealDamageEnd returned 12 damage
AttackerStateUpdate: (NPC)    99744 attacked 19 (TypeId: 4) for 12 dmg, absorbed 0, blocked 0, resisted 0.
RollMeleeOutcomeAgainst: New attack die: [MISS:1520, DODGE:1476, PARRY:0, BLOCK:0, GLANCE:0, CRIT:0, CRUSH:0]
RollMeleeOutcomeAgainst: Rolled 95, result: MISS (chance 1520)
WORLD: Sending SMSG_ATTACKERSTATEUPDATE
AttackerStateUpdate: (NPC)    99744 attacked 19 (TypeId: 4) for 0 dmg, absorbed 0, blocked 0, resisted 0.
RollMeleeOutcomeAgainst: New attack die: [MISS:1520, DODGE:1476, PARRY:0, BLOCK:0, GLANCE:0, CRIT:0, CRUSH:0]
RollMeleeOutcomeAgainst: Rolled 1490, result: MISS (chance 1520)
WORLD: Sending SMSG_ATTACKERSTATEUPDATE
AttackerStateUpdate: (NPC)    99744 attacked 19 (TypeId: 4) for 0 dmg, absorbed 0, blocked 0, resisted 0.
RollMeleeOutcomeAgainst: New attack die: [MISS:1520, DODGE:1476, PARRY:0, BLOCK:0, GLANCE:0, CRIT:0, CRUSH:0]
RollMeleeOutcomeAgainst: Rolled 9851, result
```

After he died, I moved around and somehow something got logged (while the filter still was on dead hogger. It got written on the console everytime my character moved.

```
wSTORAGE_SIZE: 29
01 00 00 00 00 DC 84 FA | 02 A2 CF 1B C6 0B E9 1B
44 2F CF 1A 42 C4 70 33 | 40 78 03 00 00
STORAGE_SIZE: 29
21 00 00 00 00 6B 86 FA | 02 2C DA 1B C6 4A 24 1C
44 09 6A 1A 42 C4 70 33 | 40 78 03 00 00
STORAGE_SIZE: 29
01 00 00 00 00 33 87 FA | 02 D5 DE 1B C6 74 54 1C
44 E9 17 1A 42 FC 47 15 | 40 78 03 00 00
STORAGE_SIZE: 29
01 00 00 00 00 27 89 FA | 02 7F E8 1B C6 8D F6 1C
44 62 38 19 42 FC 47 15 | 40 78 03 00 00
STORAGE_SIZE: 29
00 00 00 00 00 6A 89 FA | 02 CA E9 1B C6 45 0C 1D
44 3B 1E 19 42 FC 47 15 | 40 78 03 00 00
STORAGE_SIZE: 29
02 00 00 00 00 F8 8D FA | 02 CA E9 1B C6 45 0C 1D
44 3B 1E 19 42 FC 47 15 | 40 78 03 00 00
STORAGE_SIZE: 29
00 00 00 00 00 E2 8E FA | 02 E2 E6 1B C6 80 DB 1C
44 B0 58 19 42 FC 47 15 | 40 78 03 00 00
STORAGE_SIZE: 29
01 00 00 00 00 DA 92 FA | 02 E2 E6 1B C6 80 DB 1C
44 B0 58 19 42 FC 47 15 | 40 78 03 00 00
STORAGE_SIZE: 29
00 00 00 00 00 60 93 FA | 02 79 E9 1B C6 F1 06 1D
44 12 23 19 42 FC 47 15 | 40 78 03 00 00
STORAGE_SIZE: 29
20 00 00 00 00 05 97 FA | 02 79 E9 1B C6 F1 06 1D
44 12 23 19 42 FC 47 15 | 40 78 03 00 00
```
I dont know what this is, movement packets maybe? it should be filtered out since its not concerning hogger imo. (Unless it has something to do with him)

**Comment by berserkingyadis** [comment]
Then issueing this command `.server log typefilter player`

This exception pops up:
image

Call Stack:
```
 	ucrtbased.dll!00007ffaf78ef621()	Unknown
>	mangosd.exe!std::char_traits<char>::length(const char * const _First) Line 466	C++
 	mangosd.exe!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign(const char * const _Ptr) Line 2676	C++
 	mangosd.exe!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> >(const char * const _Ptr) Line 2185	C++
 	mangosd.exe!ChatHandler::HandleServerLogTypeFilterCommand(char * args) Line 644	C++
 	mangosd.exe!ChatHandler::ExecuteCommand(const char * text) Line 1268	C++
 	mangosd.exe!ChatHandler::ParseCommands(const char * text) Line 1386	C++
 	mangosd.exe!WorldSession::HandleMessagechatOpcode(WorldPacket & recv_data) Line 172	C++
 	mangosd.exe!WorldSession::ExecuteOpcode(const OpcodeHandler & opHandle, WorldPacket & packet) Line 885	C++
 	mangosd.exe!WorldSession::Update(PacketFilter & updater) Line 289	C++
 	mangosd.exe!World::UpdateSessions(unsigned int __formal) Line 1918	C++
 	mangosd.exe!World::Update(unsigned int diff) Line 1472	C++
 	mangosd.exe!WorldRunnable::run() Line 59	C++
 	mangosd.exe!MaNGOS::Thread::ThreadTask(void * param) Line 85	C++

```

**Comment by berserkingyadis** [comment]
When trying to filter multiple guids (`server log guidfilter 38 40`), only the first one gets filtered and the rest gets skipped.

The command `log` toggles filter of the current target, and if there is none, the player. (this command doesnt appear to be in the commands table)

**Comment by cyberium** [comment]
@berserkingyadis all should be fixed

**Comment by berserkingyadis** [comment]
Ok these are the current things I have observed:

1. When doing `.logtarget` with no target the player gets added to filter list (OK imo)
- Multiple log outputs like player movement (MSG_MOVE, MSG_STOP) (OK)
- UpdateVisiblility for the player (OK)
- this: (dunno if it should be logged since they appear to be errors?)
image
2. GUID filter now works with multiple IDs! (If does not warn when doing multiple identical IDs in the command tho, example: `.server log guidfilter 1 1` adds and removes from list)
3. When doing .server log filter all off the guidfilter and typefilter list does NOT get emptied, this means the logging output is still minimal. Should'nt they get emptied?
4. Typefilter is now working without crash!

**Comment by berserkingyadis** [comment]
forgot ping @cyberium

**Comment by cyberium** [comment]
This will be implemented another way

**Pull request closed without merging**
