### PR TITLE
q.10657 script

### PR DESCRIPTION
**Pull request by killerwife**
http://www.wowhead.com/quest=10657/ride-the-lightning

On being hit by lightning spell, if player has aura from quest, he will be given single quest credit. Rest is already in ACID

### CODE REVIEW

**Comment by xfurry** [comment]
@killerwife please open a PR for this on wotlk as well.
Thanks

**Comment by killerwife** [comment]
Yes but please next time merge it without merge commit :D
I will have it done in a moment.

**Comment by xfurry** [comment]
> Yes but please next time merge it without merge commit :D

Why? This is the easiest way to merge it. Just one click.

**Comment by killerwife** [comment]
Linear repository tree.

**Comment by cyberium** [comment]
Yep i hate those merge too resulting in spagetti history.
Please read -> http://endoflineblog.com/gitflow-considered-harmful

**Pull request merged**
