### PR TITLE
Update the_barrens.cpp

### PR DESCRIPTION
**Pull request by haddock1986**
added npc_beaten_corpse

### CODE REVIEW

**Comment by killerwife** [comment]
This is/will be in Database instead of C++. Not sure if exported

**Comment by haddock1986** [comment]
when i runned the mangosd.exe application it says that isn't scripted, before i added the code this message dissappears

**Comment by cyberium** [comment]
@killerwife please verify and close this.

**Comment by killerwife** [comment]
Not needed.

**Pull request closed without merging**
