### PR TITLE
[SD] Ghostlands: Correct EscortFaction for Ranger Lilatha 16295

### PR DESCRIPTION
**Pull request by AnonXS**
Part of https://github.com/cmangos/issues/issues/2133, some db stuff will be added later

[1] UpdateType: Values
[1] Object Guid: Full: 0x2030A442400FE9C00075F600007348D2 Creature/0 R3113/S30198 Map: 530 Entry: 16295 Low: 7555282
[1] UNIT_FIELD_FACTIONTEMPLATE: 250/3.5E-43 (250)
[1] UNIT_FIELD_FLAGS: 0

### CODE REVIEW

**Comment by killerwife** [comment]
Can u move the wps to creature_movement_template? Just do it in your sql, write here and I will deal with the c++ alteration.

**Comment by AnonXS** [comment]
you mean waypoint path?

**Comment by killerwife** [comment]
Y

**Comment by AnonXS** [comment]
done

**Pull request closed without merging**
