### PR TITLE
WIP: Testing Framework (pipe dream initialized)

### PR DESCRIPTION
**Pull request by BenDol**
I want to start writing some integration tests for cmangos. So I have created a simple configurable testing module for this `BUILD_TESTING`. This will allow us to make a requirement for PR changes to have tests written a long side them before they are accepted. I will expand on this more, but the framework will be fairly simple at the moment.

### Disclaimer
This may not be achievable, but for learning purposes I will be implementing this as an _educational_ activity into the web of cmangos. Feel free to criticize or comment thoughts on the approach as I am not super well versed with C++ testing frameworks as of right now. If this isn't used in the main project I will certainly be trying to use it in my `dev` project when successful.

devenv_2019-05-29_15-18-41

Thanks!

### CODE REVIEW

**Comment by BenDol** [comment]
cmangos_testing

Progress? Now have access to the whole server for testing, need to figure out how I want to submit to the packet interface or if I want to experiment another way.

**Comment by cyberium** [comment]
I'll close this one, You can continue to work on it and its very interesting if we can achieve such test.
But to keep less PR open possible i prefer to keep it close for now.

**Comment by BenDol** [comment]
Why couldn't this just remain open for people to follow the WIP? It helps for me to get input from people on progress.

**Comment by ulfgebhardt** [comment]
I agree with @BenDol 
Why ever close an PR with is not closed due to "it wont be merged" or "merged" status?
This is the type of change i'd like to see - people should be able to develop directly on this Repo to make it easier for them to contribute @cyberium 
The author clearly added `WIP` = `Work in Progress` which is the common mechanic to mark such development branches.

**Comment by killerwife** [comment]
I can't speak for @cyberium , but he was probably going along the lines of "working on less at the same time". The idea with this PR is that it seems like a huge adventure. I will reopen it myself, but do not let the PR run stale. It means by no means that we do not want it, this would be a huge benefit to everything we do.

**Comment by killerwife** [comment]
Closing due to inactivity as promised.

**Pull request closed without merging**
