### PR TITLE
Update PlayerbotAI.cpp

### PR DESCRIPTION
**Pull request by dunjeon**
Fixes bots not responding to attack commands from direct tell or in party chat.

### CODE REVIEW

**Comment by cyberium** [comment]
look like @dunjeon code is right. Something missing while porting to the core?

**Comment by dunjeon** [comment]
Mac build fails on travis-ci, but linux and windows both compile without error.

**Comment by cyberium** [comment]
Don't worry about OSX now its know and will be fixed :)

**Comment by cala** [comment]
Merged, thanks. :+1:

**Pull request merged**
