### PR TITLE
Fix Arcane Torrent mana replenishing

### PR DESCRIPTION
**Pull request by Warlockbugs**
Someone got wrong spell ids. >.<

### CODE REVIEW

**Comment by cyberium** [comment]
Are you sure this is correct?
Two same spells except effect1 SPELL_EFFECT_ENERGIZE vs SPELL_EFFECT_ENERGIZE_PCT

**Comment by Warlockbugs** [comment]
[SpellEffects] (https://github.com/cmangos/mangos-tbc/blob/master/src/game/SpellEffects.cpp#L1076)  contains script for 28730 and 28733.

**Comment by cyberium** [comment]
Ok, any clue of from where those value come then? Wotlk? Classic?

**Comment by Warlockbugs** [comment]
I am not sure exactly, my guess, one pair is meant for rogues and the other one is for mana using classes (all other blood elves). Its all got mixed and messed up. If it's true, additional fix is needed to make sure both versions correctly use dummy stacks and not replenishing mana "for free" without it (like it is atm).

**Comment by Warlockbugs** [comment]
Re-checked on fresh branch: nevermind the pr, seems to be working as intended atm. Apparently, something was broken on my side.

**Comment by killerwife** [comment]
@Warlockbugs its not :D

**Comment by cyberium** [comment]
Why its not would be a better answer ...

**Comment by killerwife** [comment]
Arcane torrent is implemented twice by mistake. Once in aura mod silence, Once in effect dummy. The correct way is for it to be implemented in Effect Dummy. Also, 28734 shouldnt restore mana, only the other one should,
 if (m_spellInfo->Id == 28734)
        return;
is missing from EffectPowerDrain

**Comment by killerwife** [comment]
@cyberium I immediately started writing that message, ^^ didnt know u both were here at the same moment.

**Comment by cyberium** [comment]
iam everywere at any moment looking over your shoulder.

**Comment by Warlockbugs** [comment]
Ok, retested the whole combination:
Arcane Torrent does not reward mana if there is no dummy stacks from Mana Tap.
Mana Tap does reward mana on use instead of just draining it from enemy and applying dummy stack (this shouldn't happen).

**Comment by killerwife** [comment]
line 1076 in SpellEffects.cpp

**Comment by Warlockbugs** [comment]
Closing this with intention to open a new one with a solution for Mana Tap. Arcane Torrent somehow works at the moment in fact, no matter a proper way or not.

**Comment by killerwife** [comment]
https://gist.github.com/killerwife/a08f1d1256f96c4f8d4d4dbdb70cd054

PR this - profit

**Comment by robinsch** [comment]
meh

**Pull request closed without merging**
