### PR TITLE
Playerbot in core

### PR DESCRIPTION
**Pull request by cala**
This PR adds @blueboy's playerbot (also known as portal) as an optional mod in CMaNGOS core.
By default, the core builds as usual, without any part of the mod code to prevent any stability or performance drawback. With the `BUILD_PLAYERBOT` cmake option, the mod will be built, embedded into the core.

I'd like people that don't use playerbot to check that they have no issues building, linking and installing the core as usual. The command `.bot add NameOfAnotherCharacterInSameAccount` should result in an error message: "no such command".

I'd also like people that intend to use playerbot to check that they have no issues building, linking and installing playerbot by adding `-DBUILD_PLAYERBOT=ON` to their cmake command. The command `.bot add NameOfAnotherCharacterInSameAccount` should then work as usual for them.

Tests for this PR should focus on building, linking and installing parts.

Original code by @blueboy and cie: https://github.com/blueboy/portaltbc

This includes all updates made to the Playerbot Classic branch for the last 4 years ported to TBC branch.

### CODE REVIEW

**Comment by evil-at-wow** [comment]
Some early Linux results after a quick pull and build: it builds on my system when I build as usual (so without playerbot), but fails to compile on the same system when I also pass `-DBUILD_PLAYERBOT=ON` to the CMake command line:

```
[ 14%] Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/AI/PlayerbotDruidAI.cpp.o
In file included from /tmp/cmangos-tbc-playerbot/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/cmangos-tbc-playerbot/src/game/PlayerBot/AI/PlayerbotDruidAI.h:22,
                 from /tmp/cmangos-tbc-playerbot/src/game/PlayerBot/AI/PlayerbotDruidAI.cpp:19:
/tmp/cmangos-tbc-playerbot/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: 'TrainerSpell' has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
                                         ^~~~~~~~~~~~
```

I didn't try to install or run the non-playerbot core yet, so I can't comment on that.

**Comment by killerwife** [comment]
Oh this will be fun to port :D Well done @cala . Time to host a cmangos stock server with 1000 fake players 🗡

**Comment by Darexon** [comment]
On Arch Linux I get this error when passing `-DBUILD_PLAYERBOT=ON`
```
[ 89%] Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/AI/PlayerbotHunterAI.cpp.o
In file included from /tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotDruidAI.h:22,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotDruidAI.cpp:19:
/tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: ‘TrainerSpell’ has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
                                         ^~~~~~~~~~~~
In file included from /tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotHunterAI.h:22,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotHunterAI.cpp:19:
/tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: ‘TrainerSpell’ has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
                                         ^~~~~~~~~~~~
[ 89%] Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/AI/PlayerbotMageAI.cpp.o
[ 90%] Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/AI/PlayerbotPaladinAI.cpp.o
In file included from /tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotMageAI.h:22,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotMageAI.cpp:19:
/tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: ‘TrainerSpell’ has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
                                         ^~~~~~~~~~~~
[ 90%] Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/AI/PlayerbotPriestAI.cpp.o
In file included from /tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotPaladinAI.h:4,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotPaladinAI.cpp:19:
/tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: ‘TrainerSpell’ has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
                                         ^~~~~~~~~~~~
[ 90%] Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/AI/PlayerbotRogueAI.cpp.o
[ 90%] Building CXX object src/game/CMakeFiles/game.dir/PlayerBot/AI/PlayerbotShamanAI.cpp.o
In file included from /tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotPriestAI.h:22,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotPriestAI.cpp:19:
/tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: ‘TrainerSpell’ has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
                                         ^~~~~~~~~~~~
In file included from /tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotRogueAI.h:22,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotRogueAI.cpp:19:
/tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: ‘TrainerSpell’ has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
                                         ^~~~~~~~~~~~
In file included from /tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotClassAI.h:24:0,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotShamanAI.h:22,
                 from /tmp/mangos-tbc/src/game/PlayerBot/AI/PlayerbotShamanAI.cpp:19:
/tmp/mangos-tbc/src/game/PlayerBot/AI/../Base/PlayerbotAI.h:696:41: error: ‘TrainerSpell’ has not been declared
     bool _HandleCommandSkillLearnHelper(TrainerSpell const* tSpell, uint32 spellId, uint32 cost);
```
The core still builds fine when I don't pass `-DBUILD_PLAYERBOT=ON`

**Comment by cala** [comment]
I fixed the build with CMake and `-DBUILD_PLAYERBOT=ON` : a header was missing, probably lost when I updated the tree structure before merging. Sorry about that.

I intend to merge this PR within two weeks as it should not be much different from what was done with the Classic branch.

**Comment by Darexon** [comment]
I can confirm that this runs and builds on Arch Linux and CentOS 7.

**Pull request merged**
