### PR TITLE
Alchemy Addition

### PR DESCRIPTION
**Pull request by Yatzii93**
Using AzerothCore as a reference.

### CODE REVIEW

**Comment by 5man999** [comment]
Whats missing is correct cost, right now it's using the cost for blacksmithing/leatherworking - I'll correct it at some point, if I don't forget :P

**Comment by evil-at-wow** [comment]
I don't think this PR is needed. We used to have this in our scripts (which might be where AzerothCore got it in the first place?), but it was removed because that gossip is now handled in the database. See scriptdev2/scriptdev2-tbc@b25943682b41 for details (and note that scriptdev2 was integrated in the core somewhere early 2017).

Did you add this because the gossip was missing, or not working as intended?

**Comment by 5man999** [comment]
It wasn't working. It just took the gold cost so I figured it wasn't implemented.

**Comment by evil-at-wow** [comment]
Starting an issue is a good idea either way I think. That makes it a known issue that can be investigated. 
As far as I'm concerned, this PR can then be closed because I think it's somewhat unlikely it will be merged, but if it remains open while the issue is being investigated, I don't mind either.

**Comment by killerwife** [comment]
All of this exists in DBScripts. There are particular spells for unlearning all this. It was removed as a result of it being changed to dbscripts. Please go look up scripts that use 41563, 41564 and 41565 in dbscripts (_on_gossip) I believe to confirm my memory @Yatzii93 .

**Pull request closed without merging**
