### PR TITLE
Fix a bug Stop Combat In Instances.

### PR DESCRIPTION
**Pull request by keyshuwen**
## 🍰 Pullrequest

creature Stop Combat In Instances.
### Proof

- None

### Issues

- Avoid escaping combat.

### How2Test

- In Instances, the attack creature, character moves a distance to escape the battle.

### CODE REVIEW

**Comment by BenDol** [comment]
Does `IsDungeon` also return true for raids? I assume its the same behavior.

**Comment by keyshuwen** [comment]
yes, 

> bool IsDungeon() const { return map_type == MAP_INSTANCE || map_type == MAP_RAID; }

**Comment by cala** [comment]
Hi, I will merge this PR as it is with the addition of a few comments because it is an improvement over the current state of the core where many dungeon encounters or event are simply broken.

However, this fix assume there is zero leash in dungeons which is false. Some indoor bosses reset if pulled too far from their original position (and some outdoor bosses do the opposite).

So we need a real leash management that can handle all these cases. In the meantime, we will use this fix.

**Comment by cala** [comment]
And because I'm a dumbass, I did not even thank you for this PR.

Thanks ! 😉

**Comment by cala** [comment]
Merged in https://github.com/cmangos/mangos-tbc/commit/6bc15c5acf8224a9da1245bc08c54ecb89a1335c
Thank you!

**Pull request closed without merging**
