### PR TITLE
Add a possibility to set a pool of creature as a target for script.

### PR DESCRIPTION
**Pull request by cyberium**
Avoiding to set explicitly a specific creature for some basic command.

You have to use SCRIPT_FLAG_BUDDY_BY_POOL (128) and dont put anything to entry. Search Radius Or Guid field will contain the pool id.

This is related to -> https://github.com/cmangos/tbc-db/commit/d57fe2b65e5420707c32d4be5c753c09ec6cac23#commitcomment-24357406

@Saltgurka @killerwife @Grz3s @cala 

This need to be tested by one of you guys i will not push it without a green light because i know it have some limitation.

I choose to select first available target that is alive. It may cause some unneeded error if no target are alive at T time.

### CODE REVIEW

**Comment by Grz3s** [comment]
haha i see now how we want to fix issues with this:
https://github.com/cmangos/tbc-db/commit/d57fe2b65e5420707c32d4be5c753c09ec6cac23#commitcomment-24357406
Very nice...
I'll look at this asap .. :)

**Comment by Grz3s** [comment]
Hi @cyberium 
First thank for this patch ..
I did test it on small test script:
```sql
-- pool target test
-- .go -2758.04 2847.733 114.10 530   -- if u want to test it by yourself

-- fresh creatures
DELETE FROM creature WHERE guid=151044;
INSERT INTO creature VALUES (151044,16769,530,1,1,0,974,-2758.04,2847.73,114.108,4.84973,25,25,0,0,4572,2705,0,2);
DELETE FROM creature WHERE guid=151045;
INSERT INTO creature VALUES (151045,1410,530,1,1,0,309,-2756.98,2837.2,115.462,1.65629,25,25,0,0,4422,2620,0,0);
DELETE FROM creature WHERE guid=151046;
INSERT INTO creature VALUES (151046,5355,530,1,1,0,1463,-2755.55,2837.99,114.683,2.12361,25,25,0,0,5527,0,0,0);
DELETE FROM creature_addon WHERE guid = 151044;
INSERT INTO creature_addon (guid, mount, bytes1, b2_0_sheath, b2_1_pvp_state, emote, moveflags, auras) VALUES 
(151044, 0, 0, 1, 16, 0, 0, NULL);

-- pools created
DELETE FROM pool_template WHERE entry = 50000;
INSERT INTO pool_template (entry, max_limit, description) VALUES
(50000,1,'test - Firewing Defender/Bloodwarder');
DELETE FROM pool_creature WHERE pool_entry = 50000;
INSERT INTO pool_creature (guid, pool_entry, chance, description) VALUES
(151046,50000,0,'test - Firewing Defender'),
(151045,50000,0,'test - Firewing Bloodwarder');

-- Warlock
DELETE FROM creature_movement WHERE id IN (151044);
INSERT INTO creature_movement (id,point,position_x,position_y,position_z,waittime,script_id,orientation) VALUES
(151044,1,-2758.04,2847.73,114.108,20000,1676990,4.84973);
DELETE FROM dbscripts_on_creature_movement WHERE id IN (1676990);
INSERT INTO dbscripts_on_creature_movement (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
--
-- search for pool -- command 31 REQ
--
(1676990, 1, 0, 0, 0, 0, 0, 50000, 128, 2000000903, 0, 0, 0, 0, 0, 0, 0, 'force pool 50000 to say smth'),
(1676990, 5, 1, 19, 0, 0, 0, 50000, 128, 0, 0, 0, 0, 0, 0, 0, 0, 'force pool 50000 to emote);
```
 if pooled target found -- all works fine:)
if no target found .. error:
```quote
 DB-SCRIPTS: Process table `dbscripts_on_creature_movement` id 1676990, command 0 has buddy 0 by pool id 50000 and no creature found in map 530 (data-flags 128), skipping.
```
 so this is ok :)

To avoid these errors we're using command 31.. that simply checks if buddy is there or not...
The same thing is req for this new pool target...
So we could update command = 31 SCRIPT_COMMAND_TERMINATE_SCRIPT
and use datalong3 (currently empty) for pool search?
This could look like this:
```sql
-- datalong = search for npc entry if provided (if 0 than search for pool id in datalong3)
-- datalong2= search distance
-- datalong3 = search for pool id
(1676990, 0, 31, 0,100,50000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'search for pool x');
```
If accepted then:
We could also move current datalong2 -- > datalong3
and then use 
datalong = search for creature
datalong2 = search for pool id
datalong3 = search radius
This would look much better i think :)

**Comment by cyberium** [comment]
Thank you very much for this excellent feedback.

There is no guarantee for any npc to be present so i think a better solution would be to hide the error in release mode. Command 31 should not be used for that specific case.
But iam ok to make command 31 compatible with pool id.

**Comment by Grz3s** [comment]
Think about situation ..where  Script is a bit longer .. and 2 npc's having a long chat...
Say that second one comes from our pool...
So not using command 31.. and only hide errors... we'll end up with situation when...
Our main creature will do his part .. where second will be missing (so this will look funny ..one npc having conversation with noone) :)
Thats why we're using command 31.. (if target not found ..there will be no conversation at all)

command 31 has  also good option:
```
* dataint  = change of waittime (MILLIESECONDS) of a current waypoint movement type (negative values will decrease time)
```
So if creature not found ... whole script can be skipped and return to begening...without waiting all time req for script.

BTW:
Reason why we're using this command in first place is fact that we dont want to see any error in console :) (and this is only option to achieve that...

**Comment by cyberium** [comment]
@Grz3s updated and added command 31 pool compatibility.
I choosed datalong3 = search for pool id.

**Comment by Grz3s** [comment]
thank you

**Comment by Grz3s** [comment]
quick update:
i used your terminate for pools Script:
```sql
DELETE FROM dbscripts_on_creature_movement WHERE id IN (1676990);
INSERT INTO dbscripts_on_creature_movement (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(1676990, 0, 31, 0, 100, 50000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'search for pool 50000'), -- search for pool
(1676990, 1, 0, 0, 0, 0, 0, 50000, 128, 2000000903, 0, 0, 0, 0, 0, 0, 0, 'force pool 50000 to say smth'),
(1676990, 5, 1, 19, 0, 0, 0, 50000, 128, 0, 0, 0, 0, 0, 0, 0, 0, 'force pool 50000 to emote');
```

And script works perfect now... no errors if noone found..
Thank You again
:+1:

**Comment by Grz3s** [comment]
@cala or @Tobschinski 
Can one of You guys Please test this patch in classic  .. otherwise it will never be added into core.. 
We need this good patch.

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/commit/89491c4fcd1c8352c772312e08f67eb2cefc3d7e

**Pull request closed without merging**
