### PR TITLE
Implement Quest 4021 Counterattack!

### PR DESCRIPTION
**Pull request by ulfgebhardt**
Scripted Counterattack! Quest 4021

Relephant Sources:

Old Attempt: https://github.com/cmangos/mangos-tbc/pull/74
Trinity: https://github.com/TrinityCore/TrinityCore/issues/5420
Unified-DB: https://github.com/unified-db/Database/issues/30
Trinity again: https://github.com/TrinityCore/TrinityCore/issues/736
MangosOne(Source): https://github.com/mangosone/server/blob/release20/src/modules/SD2/scripts/kalimdor/the_barrens.cpp#L699
Genesis: https://searchcode.com/codesearch/view/83461017/

Am willing to improve and maintain on suggestions - works like a Charm for me.

### CODE REVIEW

**Comment by killerwife** [comment]
@cala You might wanna check it out. I might not do so in the next week.
@ulfgebhardt Can you post some videos of the event? So that we have something to compare it against when testing the PR. I mean retail vids.

**Comment by ulfgebhardt** [comment]
Thats why i linked the sources. Please check out for lots of Info:

https://github.com/TrinityCore/TrinityCore/issues/5420
-> https://www.youtube.com/watch?v=710FEegH13Y

**Comment by killerwife** [comment]
Ok my bad. Ill try to make sure that someone looks at it, right now script PRs have a tendency to get a bit stale.

**Comment by ulfgebhardt** [comment]
There is actually a problem - since u can start the Event twice - will look into that, but if someone can point me out to a script where such a check is alrdy implemented i would appriciate this.

**Comment by killerwife** [comment]
Essentially every instance boss done in SD2 :D Or add a boolean to the AI. Nothing complicated.

**Comment by ulfgebhardt** [comment]
How do i obtain m_bEventStarted the in GossipHello_npc_regthar_deathgate

```
bool GossipHello_npc_regthar_deathgate(Player* pPlayer, Creature* pCreature)
{
    if(m_bEventStarted)
	return true;

```

```
the_barrens.cpp:1007:8: error: 'm_bEventStarted' was not declared in this scope
     if(m_bEventStarted)
        ^
```

**Comment by killerwife** [comment]
static_cast dynamic_cast CreatureAI* of pCreature to the AI you scripted. You can find examples in the code for that as well.

**Comment by ulfgebhardt** [comment]
Yes i ask questions 2 fast ;-)

**Comment by cala** [comment]
I'll try to look at this, but I'm unable to give an ETA for "when".

**Comment by ulfgebhardt** [comment]
Merged with new core 2 avoid conflicts

**Comment by cyberium** [comment]
If the https://github.com/cmangos/mangos-tbc/pull/74 can be closed this can too

**Comment by killerwife** [comment]
@cyberium this needs to be finished. Sadly the scale of the event and lack of data is what makes it incredibly difficult. This falls under @cala jurisdiction, and @Grz3s expressed that he might wanna do this at some point. This second one should definitely not be closed.

**Comment by cala** [comment]
I still intend to do it, I just need to find the time.
Currently, I want to finish the Zul'Gurub PR from Phatcat, then its either this PR or the Missing Diplomat one.

**Comment by cyberium** [comment]
Enough time for this PR reopen it only if you realy want to work on it.

**Comment by cala** [comment]
I'm reopening this PR.

@ulfgebhardt It is still in my pipe and I have to apologize for not handling it sooner, the same way I did not review sooner the two PRs by Zingzah for Love is in the Air event that I finished merging **today** after reviewing them for about a month, though the PRs were open for a year and a half.

Main reasons, I did not yet review your PR:
- I more often look at Classic core/DB PRs than TBC/WotLK ones so your PR is kind of forever labelled as "okay, I should do this one next" in my mind
- When I say I review something, I don't blindly click on "merge" button, I look at it, see if it's fine, can be improved, give advice and so on. Your PR is quite long, so many things to check for a quest I know little about, meaning I need to save a good period of time to look at it, research and understand it. Unfortunately, time is a very rare resource for me so it is sometimes easier for me to spend only one hour on a easy fix/PR that is very recent than on an old one that requires more work

I hope you won't take it personally and I'm moving this higher on my ToDo list.

**Comment by killerwife** [comment]
I wish you luck. In all of cmangos and TC we don't have a single sniff of this q......

**Comment by cala** [comment]
Unfortunately, this is a common situation when dealing with Classic content. 

I'll do as always: do what I can with existing descriptions and videos, do some guess work (internal spells that are still present in Classic DB are helpful for that, at least for boss encounters) and comment code as much as I can so we can improve on this later if more data pour in.

**Comment by cyberium** [comment]
With upcoming classic the missing data will be available for us. If we want to stick to the original behavior its the best choice for us.

This exemple show how its hard for even an confirmed dev that know a lot about the classic content to review this kind of PR. Ofc we the easy path is just to click on "merge" button. We usually dont choose it though.

**Comment by cala** [comment]
> With upcoming classic the missing data will be available for us. If we want to stick to the original behavior its the best choice for us

We should be cautious about that.

Of course, lots of lost/missing data will be available and I'm very eager for it. But we should also keep in mind that new Classic client will use recent packets and DBC structure from Blizz, meaning that the conclusion we can make from the sniffs may collide with what currently have and some previous choices we made in designing our actual core.

But this is off-topic.

**Comment by cala** [comment]
A small question @killerwife : I'm about to (finally) work on this PR, can you tell me where you are in your export process, please? If you are not done exporting, that's fine I'll wait until process is finished but if you are in the "fixing exporting issues" phase, I'll start working on this.

**Comment by killerwife** [comment]
Except fixes to regressions, I am done.

**Comment by cala** [comment]
Great ! Thank you. :+1:

**Comment by cala** [comment]
Hi @ulfgebhardt ,

First of all: again, my apologies for taking that long in reviewing this.

This is a nice work, with researches and it indeed seems to address the quest (at least from what I understand from it). Thank you.

I saw some changes in the code that could make it shorter and easier to read (some of these changes are related to the fact that the core obviously changed since you pushed your PR, so do not take this personally).

Do you prefer that I do the changes on a separate branch, step by step so you can see what I mean or do you prefer that I tell about them so you can do them yourself?

Secondly, I wonder why Horde Defender NPC has its AI scripted in SD2 and not in ACID. Is it only supposed to attack Kolkar Invaders and ignore all other targets?

**Comment by ulfgebhardt** [comment]
Hey @cala ,
no need to apologize. Its just good to see that this is moving forward!

Please do how you please with this PR/the contents of it. I am currently involved in other stuff so that I probl. will not be able to contribute to this in a timely manner.

Feel free to make your own PR and take the changes you like or continue on this branch. As long as the quest will be fixed it is fine with me <3

**Comment by cala** [comment]
Merged in https://github.com/cmangos/mangos-classic/commit/ac8cc7e36730b6a84f469c318ea4c29211a0daf0 and following commits.

**Pull request closed without merging**
