### PR TITLE
Remake CMake dependency structure into a more modern one

### PR DESCRIPTION
**Pull request by Warlockbugs**
Also bumps minimum supported CMake version to 3.0 as we use modern features.

Managing internal dependencies becomes much easier with link/header inheritance mechanism.

This also acts as preparation for planned OpenSSL 1.1 migration.

@cala 
This requires your approval as a Mac user. Please, let me know if you are able to get CMake 3.0+ and build this branch.

### CODE REVIEW

**Comment by cala** [comment]
CMake configuration fails on my system with this PR:
```
-- Detected 64-bit platform
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /Users/manwesulimo/toolchains/gcc-4.8.5/bin/gcc
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- GCC: SFMT enabled, SSE2 flags forced
Defaulting to release build.
-- Found Git: /usr/local/git/bin/git (found version "1.7.7") 
-- cotire 1.7.6 loaded.
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   program_options
--   thread
--   regex
-- Using mysql-config: /usr/local/mysql/bin/mysql_config
-- Found MySQL library: /usr/local/mysql/lib/libmysqlclient_r.dylib
-- Found MySQL headers: /usr/local/mysql/include
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR: Found unsuitable version "0.9.8l", but required is at least "1.0" (found /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib)
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version "0.9.8l", but
  required is at least "1.0" (found
  /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.4/Modules/FindOpenSSL.cmake:357 (find_package_handle_standard_args)
  CMakeLists.txt:240 (find_package)
```

I have the bad feeling that I will have to get sources for a newer version of another library, find how to compile and install it on my system specifically for CMaNGOS without breaking other softwares that still need/use the previous version. Again.

**Comment by cala** [comment]
And regarding CMake version, I'm using 3.4.0

**Comment by ulfgebhardt** [comment]
https://www.cvedetails.com/vulnerability-list/vendor_id-217/product_id-383/version_id-85581/Openssl-Openssl-0.9.8l.html

**Comment by Warlockbugs** [comment]
If there is no major API changes inbetween 0.9.8l and 1.0.1l, you can upgrade to 1.0.1l which will serve you until 2020. Considering you were previously linking against it with 1.0.1l windows headers, should not be a major issue.

**Comment by Warlockbugs** [comment]
If you find that 1.0.1l breaks too much stuff, we can try reducing the version requirement with a warning about vulnerabilities.

**Comment by cyberium** [comment]
>If you find that 1.0.1l breaks too much stuff, we can try reducing the version requirement with a warning about vulnerabilities.

@Warlockbugs s do it that way, i don't like much to have osx not buildable all those day. And finally iam not even sure there is much problem for any version we use as we use only crypto library.

**Comment by cala** [comment]
So, do I need to build and install OpenSLL 1.x.x? (I won't be able to do it before monday, anyway)

**Comment by cyberium** [comment]
@cala its preferable but not mandatory as far i understand

**Comment by cala** [comment]
I'll give it a try then.

**Comment by Warlockbugs** [comment]
Removed OpenSSL version requirement, added a warning instead.

**Comment by Warlockbugs** [comment]
Merged.
@cala 
If any issues with the build process persist after version requirement lift, let me know.

**Comment by cala** [comment]
@Warlockbugs 

> Removed OpenSSL version requirement, added a warning instead.

Would sound good to me but when trying to build last revision of Classic after you merged this PR, I got:
```
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   system
--   program_options
--   thread
--   regex
-- Using mysql-config: /usr/local/mysql/bin/mysql_config
-- Found MySQL library: /usr/local/mysql/lib/libmysqlclient_r.dylib
-- Found MySQL headers: /usr/local/mysql/include
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR: Found unsuitable version "0.9.8l", but required is at least "1.0.1" (found /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib)
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR: Found unsuitable version "0.9.8l", but required is at least "1.0.1" (found /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib)
CMake Error at CMakeLists.txt:247 (message):
  OpenSSL not found!


-- Configuring incomplete, errors occurred!
```
As I understand it, there is still a requirement on OpenSSL version, and not a warning. Unless I missed something.

**Comment by cala** [comment]
I updated CMakeLists.txt file to make the required version match the one on my system as a temporary workaround (core builds and starts as usual).

**Comment by Warlockbugs** [comment]
Additionally removed version from search.

**Pull request merged**
