### PR TITLE
Trash respawn when Boss is Alive

### PR DESCRIPTION
**Pull request by miraco**
https://gitlab.com/lights-vengeance/issues/-/issues/953

### Proof

- None

### Issues

- None

### How2Test

- None

### Todo / Checklist

- []

### CODE REVIEW

**Comment by AnonXS** [comment]
To me this linking should be linked to FLAG_CANT_SPAWN_IF_BOSS_DEAD        = 0x0400, because only raid npcs are hard linked to bosses and these cant respawn when the boss is in combat, but are pushed back until he is OOC again. @killerwife

**Comment by killerwife** [comment]
@AnonXS Is correct @miraco . Add this as behaviour for FLAG_CANT_SPAWN_IF_BOSS_DEAD. This is how all mobs on retail behave :) Then it will be reviewed and merged.

**Comment by miraco** [comment]
> because only raid npcs are hard linked to bosses

I am not sure about this. The npcs in normals/heroics are also linked to the boss but i dont know they can respawn when boss is inCombat

Im not even sure this fix works. Will have to update all my local files before updating this.

**Comment by killerwife** [comment]
I have a fix ready. I managed to solve this a lot more simply. Will be in next round of exports (I think it was a commit in july, and atm i finished May)

**Comment by miraco** [comment]
Sounds good, gonna close it then.

**Comment by AnonXS** [comment]
It would be nice to get all the cases together where in dungeons, respawn can walk in on a grp doing a boss, as we removed most respawn linking towards bosses in dungeons.

**Comment by miraco** [comment]
Well i guess, the only way how you can figure it out is to go on retail, kill trash and wait ~2 hours? Not sure you can find infos in sniffs or anything else

**Pull request closed without merging**
