### PR TITLE
Rework Magtheridon Fight

### PR DESCRIPTION
**Pull request by miraco**
## 🍰 Pullrequest

This will will rework Magtheridon fight, using spawn_group and spell_list for Channelers
Fix following Bugs:
Hellfire Channeller and Magtheridon will now have correct leashing
Hellfire Channeler and Magtheridon will despawn for 30 seconds when a group wipes
When all Channelers are dead, magtheridon will get instantly freed. (Confirmed on tbc classic)
Magtheridon will now roar and have a 3 seconds delay after getting released, helping tanks to pick up the boss
You cant dodge Quake Knockback with Jumping anymore

### Proof

- None

### Issues

- None

### How2Test

- None
You will need the sql data provided in here: https://github.com/cmangos/tbc-db/pull/1214

### Todo / Checklist

- [ ] With using spawn_group and flag CREATURE_GROUP_AGGRO_TOGETHER, sometimes not all Channelers will aggro together.*

This seem to be an overall  problem with spawn group and aggro together flag when group members are channeling spells, didnt want to hard code it.

### CODE REVIEW

**Comment by killerwife** [comment]
Is there any blocker for magtheridon to use spell lists? Except the obvious TODO comment.

**Comment by miraco** [comment]
Should prob be doable with spell_list, i just didnt start switching the spells into spell_list.
Just have to see how timers will be after he gets released

**Comment by miraco** [comment]
Im done for now with reworking this fight, added spell_list to magtheridon fight.

The only think i dont get working atm, is the open ToDo. This looks like an overall problem with spawn_group system blocking aggro while npcs are channelling.

**Comment by killerwife** [comment]
I looked into the TODO, and there is no spell, so I will merge PR and remove the TODO since it isnt applicable.

**Pull request merged**
