### PR TITLE
Refactoring ScriptDev

### PR DESCRIPTION
**Pull request by atidot3**
## 🍰 Pullrequest

Removing the all AI/ from game folder and make it a submodule.
Will be easier to upgrade with more modern c++.

### Proof

With SD3:
CMake output:
...
> CMaNGOS-Core revision : fef847d1e3bad973f51e767eedd9cea4f076ed1c
> Revision time stamp   : "2022-08-08T17:26:06+02:00"
> Install server to     : C:/Program Files (x86)/CMaNGOS_TBC
> Use PCH               : Yes (default)
> Build in debug-mode   : No  (default)
> Build game server     : Yes (default)
> Build login server    : Yes (default)
> Build ScriptDev       : Yes (default)
> Build AHBot           : No  (default)
> Build METRICs         : No  (default)
> Build Playerbot       : No  (default)
> Build extractors      : No  (default)
> Build RecastDemoMod   : No  (default)
> Build git_id          : No  (default)
> Build documentation   : No  (default)
...
> Configuring done
> Generating done

Build output:

> 1>game.vcxproj -> F:\World of Warcraft PVT\TBC source\tmp\mangos-tbc\build\src\game\Debug\game.lib
> 1>Génération du projet "game.vcxproj" terminée.
> 2>------ Début de la génération : Projet : WorldServer, Configuration : Debug x64 ------
> 2>mangosd.vcxproj -> F:\World of Warcraft PVT\TBC source\tmp\mangos-tbc\bin\x64_Debug\mangosd.exe
> 3>------ Génération ignorée : Projet : INSTALL, Configuration : Debug x64 ------
> 3>Projet non sélectionné dans le cadre d'une génération pour cette configuration de solution 
> ========== Build : 2 réussite(s), 0 échec(s), 9 à jour, 1 ignorée(s) ==========

without:
...
> Revision time stamp   : "2022-08-08T17:33:01+02:00"
> Install server to     : C:/Program Files (x86)/CMaNGOS_TBC
> Use PCH               : Yes (default)
> Build in debug-mode   : No  (default)
> Build game server     : Yes (default)
> Build login server    : Yes (default)
> Build ScriptDev       : No
> Build AHBot           : No  (default)
> Build METRICs         : No  (default)
> Build Playerbot       : No  (default)
> Build extractors      : No  (default)
> Build RecastDemoMod   : No  (default)
> Build git_id          : No  (default)
> Build documentation   : No  (default)
...
> Setting up zlib ...
> zlib 1.2.12 successfully installed!
> Configuring done
> Generating done

Build output:
10>mangosd.vcxproj -> F:\World of Warcraft PVT\TBC source\tmp\mangos-tbc\bin\x64_Debug\mangosd.exe
11>------ Début de la génération : Projet : ALL_BUILD, Configuration : Debug x64 ------
11>Building Custom Rule F:/World of Warcraft PVT/TBC source/tmp/mangos-tbc/CMakeLists.txt
12>------ Génération ignorée : Projet : INSTALL, Configuration : Debug x64 ------
12>Projet non sélectionné dans le cadre d'une génération pour cette configuration de solution 
========== Build : 11 réussite(s), 0 échec(s), 0 à jour, 1 ignorée(s) ==========

### Issues
- None

### How2Test

Using git:
- git clone --recursive https://github.com/atidot3/mangos-tbc.git -b lastest
- configure with cmake
- build
- enjoy

### Todo / Checklist
- Make a new cmangos-tbc repo called SD3 or similar and replace mine with it in .gitmodules

### CODE REVIEW

**Comment by killerwife** [comment]
Ok there are a few things to unpack here and @cyberium you should pitch in as well.

First of all, submodules only make sense when you are reusing a submodule in multiple projects. We cannot do that since these scripts are all per-expansion. Perhaps explain your rationale. From experience, submodules are a massive noob trap and should be used very lightly.

Next, why the increment to SD3 if I might ask. SD3 is a MaNGOS thing not cMaNGOS.

And lastly, how would it aid modernization over the current state of affairs. I kinda miss the point of that as well.

**Comment by atidot3** [comment]
Hi,

Thanks for your fast reply.


First yes you can make one submodule for vanilla / tbc / wotlk / cata / mop etc it just need to add some cmake rules such as
from official SD3 repo so it makes sense and is easier to manage / upgrade:
`# --- NOT FOR ZERO ---
IF(("${MANGOS_EXP}" STREQUAL "TBC") OR ("${MANGOS_EXP}" STREQUAL "WOTLK") OR ("${MANGOS_EXP}" STREQUAL "CATA") OR ("${MANGOS_EXP}" STREQUAL "MISTS"))
#Instance: Caverns of Time - Black Morass
file(GLOB sources_instance_k_cot_bm scripts/kalimdor/caverns_of_time/dark_portal/*.cpp scripts/kalimdor/caverns_of_time/dark_portal/*.h)
  LIST(APPEND mangosscript_LIB_SRCS ${sources_instance_k_cot_bm})
  source_group("Kalimdor Scripts\\Instances\\Caverns of Time\\Black Morass" FILES ${sources_instance_k_cot_bm})`

As you can see in this first version i did not bother with it i just wanted to make is iso functionnal with TBC first.

I increment it to SD3 since its called SD2 in it but its fine it can be reverted or renamed.

The point is to allow more scripting possibility on all version from one same repository and fixes at the same time.
i already managed to add few new function as:

`void OnPlayerLogin(Player* pPlayer);
void OnPlayerLogout(Player* pPlayer);
void OnPlayerPreUpdate(Player* pPlayer, const uint32& diff);
void OnPlayerUpdate(Player* pPlayer, const uint32& diff);
void OnPlayerPostUpdate(Player* pPlayer, const uint32& diff);
void OnPlayerKillUnit(Player* pPlayer, const Unit* unit);
void OnPlayerPvPKill(Player* pPlayer, Player* pVictim);
void OnPlayerXpGain(Player* pPlayer, const uint32& xp_gain);
void OnPlayerLevelUp(Player* pPlayer);
bool OnPlayerItemLoot(Player* pPlayer, Item* pItem);`

But i got bored when i saw i had to do it for all repository instead of one, so i decided to just make a submodule.

**Comment by insunaa** [comment]
Some instances work differently across cores, some cores may get some updates to some system that would then break other cores if the SD2 submodule would be updated together with that one core.

**Comment by atidot3** [comment]
Some instances work differently across cores, some cores may get some updates to some system that would then break other cores if the SD2 submodule would be updated together with that one core.

> Some instances work differently across cores, some cores may get some updates to some system that would then break other cores if the SD2 submodule would be updated together with that one core.

Never said it was an easy task, just want to make it smarter not harder if we can merge all the scripts together beside having new repository every wow version.

> ```
> void OnPlayerLogin(Player* pPlayer);
> void OnPlayerLogout(Player* pPlayer);
> void OnPlayerPreUpdate(Player* pPlayer, const uint32& diff);
> void OnPlayerUpdate(Player* pPlayer, const uint32& diff);
> void OnPlayerPostUpdate(Player* pPlayer, const uint32& diff);
> void OnPlayerKillUnit(Player* pPlayer, const Unit* unit);
> void OnPlayerPvPKill(Player* pPlayer, Player* pVictim);
> void OnPlayerXpGain(Player* pPlayer, const uint32& xp_gain);
> void OnPlayerLevelUp(Player* pPlayer);
> bool OnPlayerItemLoot(Player* pPlayer, Item* pItem);
> ```
> 
> what is the point of these in a ScriptDev context?

Allow community to be more free with scripts etc it wont change how the base core works but allow to make more advanced script than it is today.


I understand thats a big change, i just wanted to provide some help regardless of the complexity to manage several repository at the same time.

**Comment by insunaa** [comment]
> Allow community to be more free with scripts etc it wont change how the base core works but allow to make more advanced script than it is today.
> 
> I understand thats a big change, i just wanted to provide some help regardless of the complexity to manage several repository at the same time.

I get that, but I mean what do these specific functions achieve? I for the life of me cannot imagine a use for them, which may well be because of my limited imagination. So I'm curious what use they *do* have, at least from your point of view

**Comment by killerwife** [comment]
Well the complexity is kinda self imposed. The main reason being a very clear divide between the scripts in each expansion. A ton of them are the same yes, but for example when you move from tbc to wotlk and take spell scripts for example, there are MASSIVE changes which would be quite a mess to maintain in one file. Next, the supporting DB tables for scripts are not the same across expansions, for example, for some inexplicable reason, TBC chess event piece charm spell is fundamentally different from the one in wotlk. The list goes on. Whats more, very often its better to leave something untouched and in a working condition than forcibly modernize it. Look at kaelthas in TBC and you will understand what that means. Yes, its terrible spaghetti, but the script is so rigorously tested that it hasnt broken in the last 4 years since I wrote it.

Ironically, the submodule sounds like a ton more work to make it work all in one expansion. And I dont mean to belittle the others in cmangos, there are very few people who 1. care for all the expansions (which your submodule workflow would force them to, else they would break something possibly or make it non blizzlike) and 2. have an actual working knowledge to know what belongs in what expansion. Thats why we leave it within the scope of each core, classic, tbc, wotlk.

And when it comes to the extensibility, that one is not exclusive to this submodule workflow. This PR would make more sense perhaps once all 3 versions run on classic clients, because the protocol for those is remarkably similar, however for legacy per-expansion emulation I just do not see the benefit. Especially when in my day to day operation I see people struggle with submodules terribly, and historically scripters are the one with the least C++ knowledge. I am not saying however that other applications might not be in the cards, I just do not see the benefits of this one in particular.

I wonder what the old man will say.

**Comment by atidot3** [comment]
> > Allow community to be more free with scripts etc it wont change how the base core works but allow to make more advanced script than it is today.
> > I understand thats a big change, i just wanted to provide some help regardless of the complexity to manage several repository at the same time.
> 
> I get that, but I mean what do these specific functions achieve? I for the life of me cannot imagine a use for them, which may well be because of my limited imagination. So I'm curious what use they _do_ have, at least from your point of view
> 
> In what kind of creature/spell/gameobject script would it be important to be informed if a player just logged in, or updated, or achieved a pvp kill, or gained a level up or gained xp or looted items?
> 
> Don't get me wrong, it's great that you're contributing.

To be honest im not really that imaginative to answer that but im pretty sure you can find alot of script on other core that use such functions.



> Well the complexity is kinda self imposed. The main reason being a very clear divide between the scripts in each expansion. A ton of them are the same yes, but for example when you move from tbc to wotlk and take spell scripts for example, there are MASSIVE changes which would be quite a mess to maintain in one file. Next, the supporting DB tables for scripts are not the same across expansions, for example, for some inexplicable reason, TBC chess event piece charm spell is fundamentally different from the one in wotlk. The list goes on. Whats more, very often its better to leave something untouched and in a working condition than forcibly modernize it. Look at kaelthas in TBC and you will understand what that means. Yes, its terrible spaghetti, but the script is so rigorously tested that it hasnt broken in the last 4 years since I wrote it.
> 
> Ironically, the submodule sounds like a ton more work to make it work all in one expansion. And I dont mean to belittle the others in cmangos, there are very few people who 1. care for all the expansions (which your submodule workflow would force them to, else they would break something possibly or make it non blizzlike) and 2. have an actual working knowledge to know what belongs in what expansion. Thats why we leave it within the scope of each core, classic, tbc, wotlk.
> 
> And when it comes to the extensibility, that one is not exclusive to this submodule workflow. This PR would make more sense perhaps once all 3 versions run on classic clients, because the protocol for those is remarkably similar, however for legacy per-expansion emulation I just do not see the benefit. Especially when in my day to day operation I see people struggle with submodules terribly, and historically scripters are the one with the least C++ knowledge. I am not saying however that other applications might not be in the cards, I just do not see the benefits of this one in particular.
> 
> I wonder what the old man will say.

If i'm not mistaking, spells are cast by the core not the scriptdev.

```
void random_boss()
{
     if (CastWhatever(target, spell_id) == cast_ok) => call core.exe wich will handle his own dbc and structure.
         // -> continue
}
```

All core must have the same prototype from CastWhatever but the script lib never use any dbc, its just script definition with timer enum spell_id aura_id etc etc.

Same for escort wich only stores the waypoint to transmit to the core sTravelMrg etc.

**Comment by cyberium** [comment]
Pro:
- i like the idea to have all same script in one single place.
- i like a lot these new hooks you proposed. They can be used to remove some of our hardcoded stuff like "Honorless Target" could be handled more nicely

Cons:
- i "personally" dont like submodule path and i think we should try to avoid it. Better try to use FetchContent feature of CMAKE
- i dont like those #IF THEN ELSE processor for script. Its already complex enough for other core part. This can be resolved by some overwrite, so vanilla script folder can be overwrited by TBC one and so on.
- some core dont work same as earlier expansion and its hard to get exactly same script across all expansion, That need more work to be able to generalize that.
- We try to make less script in SD2 and more and more script doable in DB. So that work is going to wrong direction regarding that point. Using DB will permit one day to have an easy tool to implement whatever script we want. That would never be possible in SD2.

Thank you a lot for this PR. But as you see is more cons than pro on my side.

**Comment by atidot3** [comment]
> Pro:
> 
> * i like the idea to have all same script in one single place.
> * i like a lot these new hooks you proposed. They can be used to remove some of our hardcoded stuff like "Honorless Target" could be handled more nicely
> 
> Cons:
> 
> * i "personally" dont like submodule path and i think we should try to avoid it. Better try to use FetchContent feature of CMAKE
> * i dont like those #IF THEN ELSE processor for script. Its already complex enough for other core part. This can be resolved by some overwrite, so vanilla script folder can be overwrited by TBC one and so on.
> * some core dont work same as earlier expansion and its hard to get exactly same script across all expansion, That need more work to be able to generalize that.
> * We try to make less script in SD2 and more and more script doable in DB. So that work is going to wrong direction regarding that point. Using DB will permit one day to have an easy tool to implement whatever script we want. That would never be possible in SD2.
> 
> Thank you a lot for this PR. But as you see is more cons than pro on my side.

No problemo i totaly understand your cons, thanks to the team taking time to analyze my PR and answering 👍🏻

**Comment by insunaa** [comment]
I hope this doesn't discourage you from contributing. It's a good idea in principle for sure.
Never hurts to have someone thinking outside of the box. If you haven't already, feel free to join our Discord. It's a good place to discuss ideas like this

**Comment by killerwife** [comment]
However I would like to point out that we seriously feel you on the duplication point. It needs to be said we arent a community of programming experts, even if perhaps the maintainers know what they are doing. There are people who will get booby trapped with git pull --recurse-submodules because they dont even know a normal git pull.

The old man however has a good point, in the last 2 years there has been a bit of a tech boom when it comes to generic DB APIs, spawn_group, creature_spell_list, spell_scripts (altho these are c++ only for now, they still reduce code dependance, however these prolly vary the most across expansions), and many more that I cant think of right now, that basically replace a lot of c++ that people (including me) had to emulate with per-script code because it didnt exist. As such, what definitely reduces maintenance complexity is actually removing code and moving code where it causes fewer merge errors. I have no problems with punching through 100 cherry picks in 30 minutes if none cause merge errors. Such a blatant example is when I joined in 2016, every commit in spelleffects.cpp from any core to another caused merge errors. Nowadays, only wotlk is still being a bich, and even that is now leagues better. I also separated some stuff to wotlk specific file, (i think it was spell_scripts_wotlk) because wotlk will have a massive uptick in spell scripts in the future and same with GO scripts. These kinds of changes are what reduce the complexity of maintenance the most but have to be done simultaneously across all 3 expansions.

And lastly there is one more less apparent reason. When you do a change like this, you murder all git history. For example we have no git history for sd2 for the pre-merge in 2016 (or 17). Git blame can be instrumental in tracking down a broken change when you are not the author. Anyway, I am closing this, because as cyberium said, it outweighs the pros, but I want you to know we are painfully aware that this is an issue. Just that there are perhaps easier steps to take first in that direction.

**Comment by atidot3** [comment]
> I hope this doesn't discourage you from contributing. It's a good idea in principle for sure. Never hurts to have someone thinking outside of the box. If you haven't already, feel free to join our Discord. It's a good place to discuss ideas like this
> 
> Edit: Also for the future: If you want to contribute a feature that you want across multiple cores, it's enough to implement it in one core and in the PR requesting that the feature be cherry-picked across other cores. Takes a bit more time for our devs, but features will nevertheless be replicated across cores, without you having to make them anew for every core

Will definitly join and no im not discouraged dont worry happend alot on R&D where i work ;).



> However I would like to point out that we seriously feel you on the duplication point. It needs to be said we arent a community of programming experts, even if perhaps the maintainers know what they are doing. There are people who will get booby trapped with git pull --recurse-submodules because they dont even know a normal git pull.
> 
> The old man however has a good point, in the last 2 years there has been a bit of a tech boom when it comes to generic DB APIs, spawn_group, creature_spell_list, spell_scripts (altho these are c++ only for now, they still reduce code dependance, however these prolly vary the most across expansions), and many more that I cant think of right now, that basically replace a lot of c++ that people (including me) had to emulate with per-script code because it didnt exist. As such, what definitely reduces maintenance complexity is actually removing code and moving code where it causes fewer merge errors. I have no problems with punching through 100 cherry picks in 30 minutes if none cause merge errors. Such a blatant example is when I joined in 2016, every commit in spelleffects.cpp from any core to another caused merge errors. Nowadays, only wotlk is still being a bich, and even that is now leagues better. I also separated some stuff to wotlk specific file, (i think it was spell_scripts_wotlk) because wotlk will have a massive uptick in spell scripts in the future and same with GO scripts. These kinds of changes are what reduce the complexity of maintenance the most but have to be done simultaneously across all 3 expansions.
> 
> And lastly there is one more less apparent reason. When you do a change like this, you murder all git history. For example we have no git history for sd2 for the pre-merge in 2016 (or 17). Git blame can be instrumental in tracking down a broken change when you are not the author. Anyway, I am closing this, because as cyberium said, it outweighs the pros, but I want you to know we are painfully aware that this is an issue. Just that there are perhaps easier steps to take first in that direction.

Yea i understand your point dont worry,
Just for maybe later usage you can create new repository with history without any issue nowday:

> cd repo2
> git checkout master
> git remote add remote1 url-of-repo1
> git fetch remote1
> git merge remote1/master --allow-unrelated-histories
> git remote rm remote1
All done :)

Anyway thanks again ! 👍🏻

**Pull request closed without merging**
