### PR TITLE
Fix Rend Blackhand gate if Gyth is killed before..

### PR DESCRIPTION
**Pull request by BillytheOrc**
Rend Blackhand

### CODE REVIEW

**Comment by killerwife** [comment]
1. Tabs
2. How would it be possible to skip it. Thats the critical issue here instead. It sounds like some faction change or flags or something missing.

**Comment by BillytheOrc** [comment]
Sorry you don't like my dirty tabbing </3

It's possible to skip it at level 70 if people were to dualburst the boss with a big frostbolt or something.

**Comment by BillytheOrc** [comment]
Oh, it should also be mentioned that Rend Blackhand needs a C++ script to start an instance encounter. Without that, this script always opens the gate. 

I'll work on a Rend script today, assuming I can fix my ugly tabbing :p

**Comment by killerwife** [comment]
You polluted the PR with another commit. You need to make one branch per one PR and never PR from master branch.

Next, as mentioned on reddit, until Gyth summons Rend, Gyth needs to be invulnerable, and stop at 1 hp. It can be done using DamageTaken and examples are all over the core. Please clean up the PR and adjust the script accordingly.

**Comment by cyberium** [comment]
This was abandoned so i'll just put a reminder to @killerwife if he is interested to take something from this.

**Pull request closed without merging**
