### PR TITLE
Core/Unit: Fix a bug Stop Combat In Instances.

### PR DESCRIPTION
**Pull request by keyshuwen**
## 🍰 Pullrequest

creature Stop Combat In Instances.

### Proof

- None

### Issues

- Avoid escaping combat.

### How2Test

- In Instances, the attack creature, character moves a distance to escape the battle.

### CODE REVIEW

**Comment by killerwife** [comment]
Please put it inside IsLeashingTarget. That's what this method is supposed to emulate.

**Comment by cala** [comment]
I agree with @killerwife this should be in `IsLeashingTarget()`. This is a good start but will only fix issue for NPCs in dungeons, not for outer world NPCs. This will also prevent any leashed NPC in instance maps to evade on leashing because a complete leash code is still missing. 

I've been evaluating a small fix on my side for the past weeks using leash field in `creature_template` to select which NPCs should ignore leashing and which ones are eligible to it. This allows to have the code working to whatever NPC I want. However, as long as proper leash code is missing, I'm uneasy with forcing the use of a DB field as a selector (though I have the gut this is a good approach).

We can put your code or mine as a temporary solution.

**Comment by keyshuwen** [comment]
Thank you for your advice.

**Comment by killerwife** [comment]
You don't need to close the PR. Force push into the PR branch.

**Comment by keyshuwen** [comment]
emmm......Sorry

**Pull request closed without merging**
