### PR TITLE
Update azuremyst_isle.cpp

### PR DESCRIPTION
**Pull request by haddock1986**

### CODE REVIEW

**Comment by killerwife** [comment]
This script is done in DB afaik. @Grz3s right?

**Comment by haddock1986** [comment]
it was taken from https://github.com/scriptdev2/scriptdev2-tbc old release

**Comment by killerwife** [comment]
Scriptdev is merged to core. Those sources are obsolete.

**Comment by haddock1986** [comment]
i looked for changes and i discovered this changes that could be usefull

**Comment by killerwife** [comment]
Yes but those scripts were moved to database as part of generalization process.

**Comment by cyberium** [comment]
Thank for you contribution anyway :)

**Pull request closed without merging**
