### PR TITLE
Replace GetTypeId() == TYPEID_PLAYER && GetTypeId() != TYPEID_PLAYER

### PR DESCRIPTION
**Pull request by BenDol**
## 🍰 Pullrequest
xyz->IsPlayer() and !xyz->IsPlayer()

Where's wally

### Todo / Checklist
- [X] Internal Proof Read
- [ ] Reviewer Proof Read

### CODE REVIEW

**Comment by killerwife** [comment]
Do not merge this until I give it a go. It would make my exports a huge pain. I will merge this myself when I am done with them.

**Comment by BenDol** [comment]
Wasn't sure if submissions like this are appreciated, so feel free to close it if its too much of a problem.

**Comment by BenDol** [comment]
Once you are done back porting from VoA I will resolve all the merge conflicts here.

**Comment by cyberium** [comment]
This will need more work now to merge than using find and replace so closing this for now.
Need to be done tho.

**Pull request closed without merging**
