### PR TITLE
Implement GossipSelect with items as senders

### PR DESCRIPTION
**Pull request by Lillecarl**
This allows you to create items that handle GossipMenus just like with creatures.

### CODE REVIEW

**Comment by killerwife** [comment]
Hm, where in the game is this required?

**Comment by Lillecarl** [comment]
Nowhere at all, it'd be to allow people to implement their own things.

**Comment by killerwife** [comment]
Ugh, I believe there is a strict "no custom things" policy when it comes to scripting. But ask @xfurry and @cyberium . I would prefer to not be the one making this decision.

**Comment by Lillecarl** [comment]
We'll see what they say :-)

**Comment by cyberium** [comment]
Thank you, but we have enough to deal instead of this new custom feature.

**Pull request closed without merging**
