### PR TITLE
Fix Mac build

### PR DESCRIPTION
**Pull request by Lillecarl**
Without extra warning fixes and such.

### CODE REVIEW

**Comment by Lillecarl** [comment]
Tested with Qt Creator on my Macbook too, so not just travis.

**Comment by Lillecarl** [comment]
@cyberium 
Do you see any issues with the changes here? Otherwise it'd be nice for potential Mac user to be able to build cmangos.

**Comment by cyberium** [comment]
I see nothing wrong. You did a grat job. However i will not merge this without @cala feedback because i know it may broke at least his build. So be patient please ;)
You have time now to prepare next PR :P

**Comment by cala** [comment]
Sorry, I'm busy at the moment. I'll try to test this this week end or coming week and report back asap.

**Comment by Lillecarl** [comment]
@cala is using a very nonstandard setup, also it doesn't work for cala as it is atm without mods either. 

FYI

**Comment by cyberium** [comment]
AFAIK it work for @cala without any mod currently. Maybe he can confirm that.

**Comment by Inifield** [comment]
Doesn't cala use snow leopard tho ? we are at sierra and lots of things have changed

**Comment by cyberium** [comment]
> Doesn't cala use snow leopard tho ? we are at sierra and lots of things have changed

And?
Something more constructive to say?
What about for any reason we decide all to support only snow leopard from now? Or windows vista?
Or windows 10? Or armbian?

**Comment by Inifield** [comment]
If you decide to only support older version only, you wouldn't adapt code to C++11 standard, anyway I only wanted to know which version of mac os x Cala was using because I thought the mac os x build was fixed a long time ago. I'm not sure if you are pissed at me for some reason but it was merely to get information unless it's a crime to ask...

**Comment by Lillecarl** [comment]
Not implementing support for the latest stable version of apples operating system because it might break support for an older version doesn't make sense to me, and if it's an issue... Then we could resolve the issues with the older version when they're brought up.

Then agian, I'm not in any position to say anything here, I'm just trying to contribute upstream... Which is always simple and straightforward.

**Comment by cyberium** [comment]
A bit of clarify:
- I have absolutly no interest on any apple build. So all here is to make you, cmangos users/helper, happy.
- My concern is, our cores working on most possible system.
- Supporting latest is indeed nice.
- Supporting one of the bigger cmangos contributor is better ;)
- So i take care of cmangos devs can still build and test the core with their hardware/os. I think its not a crime too.

I hope its more clear.
So iam not ready to implement code if cost is too high.
Sorry if i sound "pissed" its not the case. (My english level doesnt help me sometimes)

@Lillecarl fair enough and i repeat, code sound good and i'll try to implement it and fix it for @cala  if its possible.

**Comment by cala** [comment]
All content for this PR having been removed, it will be hard for me to finally test this, I had scheduled it for tonight. 😿

**Pull request closed without merging**
