### PR TITLE
Implement experience multiplier

### PR DESCRIPTION
**Pull request by killerwife**
Selfexplanatory

### CODE REVIEW

**Comment by Phatcat** [comment]
Thank you!

**Comment by Phatcat** [comment]
this seems too simple, though... where is the actual exp calculation being done?

**Comment by Fabi** [comment]
https://github.com/cmangos/mangos-tbc/blob/master/src/game/Formulas.h#L110

**Comment by Phatcat** [comment]
That is where it should be applied imo

**Comment by Phatcat** [comment]
that is exactly where it fits, together with `sWorld.getConfig(CONFIG_FLOAT_RATE_XP_KILL)`

https://github.com/cmangos/mangos-tbc/blob/master/src/game/Formulas.h#L124

Probably that whole function could do with a small lift-up =)

**Comment by Phatcat** [comment]
Implemented.

**Pull request closed without merging**
