### PR TITLE
Update auras when applying temporary enchantments

### PR DESCRIPTION
**Pull request by insunaa**
## 🍰 Pullrequest

This PR updates the status of all Auras for the client when a temporary enchantment occurs.
This will cause the `UNIT_AURA` API-Event to fire on the client, notifying all Addons that a change has taken place and that there are values that can be updated.

### How2Test

- Cast `Windfury Weapon` repeatedly
- use `/etrace start`
- Cast `Windfury Weapon` repeatedly, again
- Notice that the `UNIT_AURA` API-Event fires.

### CODE REVIEW

**Comment by killerwife** [comment]
Why not notify about only the unit aura again and not about all of them, you are basically spamming client with possibly hundreds of packets.

**Comment by insunaa** [comment]
Because temporary enchantments don't come with Auras, as far as I can tell. (At least I haven't been able to extract a spellauraholder in any part of the process of applying a temporary enchantment)

**Comment by killerwife** [comment]
Incorrect, SpellItemEnchantment.dbc, 283 - Windfury 1 - spell Id 33757

**Comment by insunaa** [comment]
OK? So how do I get to that spell/aura ID from the `m_spellInfo`?
I don't want to hard-code the spell IDs if I don't need to

**Comment by killerwife** [comment]
We already apply them on enchant apply, Player::ApplyEnchantment check ITEM_ENCHANTMENT_TYPE_EQUIP_SPELL

**Comment by insunaa** [comment]
added a change that should do what you suggest, but it doesn't work

**Comment by killerwife** [comment]
Well then compare sniff with packetlog, and see whats being sent, debug packetlog 1, and parse it with wpp

**Comment by killerwife** [comment]
And set packetlog in mangosd conf

**Comment by insunaa** [comment]
There's nothing being sent because the enchant_spell_id is not the spell id that causes the aura you linked earlier, so it doesn't find an auraholder for it

**Comment by insunaa** [comment]
nvm that was incorrect, it *is* being sent, but it doesn't cause the correct client response. let me check

**Comment by insunaa** [comment]
ah yes, I'm dumb. this here is stopping it from being sent:
image

**Comment by insunaa** [comment]
can't get it to work even if I remove this requirement entirely. the aura is both passive and outside of the max aura slot.
The packetlog config doesn't seem to work at all, but from what I gather the aura duration update is still either never received or discarded for some reason.
In any case the `UNIT_AURA` event never triggers for Windfury enchants for example

**Comment by killerwife** [comment]
TBC parsing isnt perfect, you can easily fix the parsing in WPP and make a pull request there as you need to investigate some issue. Do investigate it more :P

**Pull request closed without merging**
