### PR TITLE
Implement variable length dbscript string logic

### PR DESCRIPTION
**Pull request by killerwife**
This enables us to have infinite number of db_script_string for one dbscript entry.

Example of how it works
DELETE FROM dbscript_string_template WHERE id IN(1);
insert into dbscript_string_template values
(1,2000005362),
(1,2000005345);

-- 58199

UPDATE creature SET MovementType=2 WHERE guid = 58199;
DELETE FROM creature_movement WHERE id IN(58199);
INSERT INTO creature_movement VALUES(58199,1,-287.705,2916.198,-58.693,0,58199,0,0,0,0,0,0,0,3.402,0,0);
DELETE FROM dbscripts_on_creature_movement WHERE id IN(58199);
INSERT INTO dbscripts_on_creature_movement VALUES(58199,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,'TEST_STRING_TEMPL');

.tele hellfire
below there is an orc who will now randomly say a string using new tech

### CODE REVIEW

**Comment by Inifield** [comment]
Make sense, good work

**Comment by killerwife** [comment]
Has one bug, db_script_string unused errors. Putting it here so i dont forget about it.

**Comment by xfurry** [comment]
Can you give an example of the use case for this.

**Comment by killerwife** [comment]
Trash in The Eye, various SD2 scripts that are there only because of string limit.

**Comment by killerwife** [comment]
Additional Feature - PathId support for creature_movement_template -
Core support was already available, just DB support was never added. SQL required to test it in hellfire -

ALTER TABLE creature_movement_template ADD pathId int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Path ID for entry' AFTER entry, DROP PRIMARY KEY, ADD PRIMARY KEY (entry, pathId, point);

DELETE FROM dbscripts_on_spell WHERE id IN(22659);
INSERT INTO dbscripts_on_spell(id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(22659,0,10,448,0,1,0,0,0,0,0,0,0,-285.6,2918.6,-59.022,4.48,'Summon Test Hogger for WP Path');

DELETE FROM creature_movement_template WHERE entry IN(448);
INSERT INTO creature_movement_template(entry, pathId, point, position_x, position_y, position_z, waittime, script_id, textid1, textid2, textid3, textid4, textid5, emote, spell, orientation, model1, model2) VALUES
('448', '0', '1', '-282', '2903.428', '-56.545', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'),
('448', '1', '1', '-266', '2920.456', '-58.886', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');

**Pull request closed without merging**
